import csv
import random


word_data = [
    ("خانه (khāneh) - khāneh", "Home"),
    ("خوراک (khōrāk) - khōrāk", "Food"),
    ("آب (āb) - āb", "Water"),
    ("کتاب (ketāb) - ketāb", "Book"),
    ("دوست (dūst) - dūst", "Friend"),
    ("خانواده (khānavāde) - khānavāde", "Family"),
    ("شغف (sheghaf) - sheghaf", "Passion"),
    ("کار (kār) - kār", "Work"),
    ("زبان (zabān) - zabān", "Language"),
    ("دانشگاه (dāneshgāh) - dāneshgāh", "University"),
    ("مدرسه (madrese) - madrese", "School"),
    ("کامپیوتر (kāmputar) - kāmputar", "Computer"),
    ("موبایل (mobāyl) - mobāyl", "Mobile phone"),
    ("خودرو (khodrō) - khodrō", "Car"),
    ("مترو (metro) - metro", "Metro"),
    ("قهوه (ghahveh) - ghahveh", "Coffee"),
    ("چای (chāy) - chāy", "Tea"),
    ("خواب (khāb) - khāb", "Dream"),
    ("عشق (eshq) - eshq", "Love"),
    ("خنده (khande) - khande", "Laughter"),
    ("خداحافظ (khodāhāfez) - khodāhāfez", "Goodbye"),
    ("صبح (sobh) - sobh", "Morning"),
    ("شب (shab) - shab", "Night"),
    ("رستوران (restorān) - restorān", "Restaurant"),
    ("میوه (miveh) - miveh", "Fruit"),
    ("سبزی (sabzi) - sabzi", "Vegetable"),
    ("خوابگاه (khābgaah) - khābgaah", "Dormitory"),
    ("حقیقت (haqiqat) - haqiqat", "Truth"),
    ("خبر (khabar) - khabar", "News"),
    ("گردشگری (gardeshgari) - gardeshgari", "Tourism"),
    ("هواپیما (havāpeymā) - havāpeymā", "Airplane"),
    ("سینما (sīnemā) - sīnemā", "Cinema"),
    ("آینه (āyene) - āyene", "Mirror"),
    ("موسیقی (mūsīqī) - mūsīqī", "Music"),
    ("آرامش (ārāmes̱h) - ārāmes̱h", "Peace"),
    ("حیوان (havvān) - havvān", "Animal"),
    ("پارک (pārk) - pārk", "Park"),
    ("گل (gol) - gol", "Flower"),
    ("هوا (havā) - havā", "Weather"),
    ("تاریخ (tārikh) - tārikh", "History"),
    ("شنا (shenā) - shenā", "Swimming"),
    ("قلب (ghalb) - ghalb", "Heart"),
    ("خنک (khonak) - khonak", "Cool"),
    ("گرم (garm) - garm", "Warm"),
    ("کوه (kūh) - kūh", "Mountain"),
    ("دریا (daryā) - daryā", "Sea"),
    ("آفتاب (āftāb) - āftāb", "Sun"),
    ("ماه (māh) - māh", "Moon"),
    ("ستاره (setāre) - setāre", "Star"),
    ("شبنم (shabnam) - shabnam", "Dew"),
    # ... (previous entries)

    # Continue with the next batch
    ("سلامتی (salamatī)", "Health"),
    ("جشن (jashn)", "Celebration"),
    ("خوشحالی (khoshhālī)", "Happiness"),
    ("شجاعت (shojā'at)", "Courage"),
    ("آزادی (āzādī)", "Freedom"),
    ("موفقیت (mofaqqīyat)", "Success"),
    ("جادو (jādū)", "Magic"),
    ("راز (rāz)", "Secret"),
    ("سرگرمی (sargarmī)", "Entertainment"),
    ("حس (hes)", "Feeling"),
    ("حرارت (harārat)", "Heat"),
    ("رقص (raqs)", "Dance"),
    ("تنهایی (tanhaa'ī)", "Loneliness"),
    ("آرزو (ārzū)", "Wish"),
    ("سکوت (sokūt)", "Silence"),
    ("گلابی (gelābī)", "Peach"),
    ("معمولی (ma'mūlī)", "Ordinary"),
    ("شگفت‌انگیز (shogofte-angīz)", "Amazing"),
    ("پیشرفت (pishraft)", "Progress"),
    ("نقاشی (naqāshī)", "Painting"),
    ("نوشیدنی (noshīdani)", "Beverage"),
    ("کودک (kūdak)", "Child"),
    ("پنجره (panjere)", "Window"),
    ("باران (bārān)", "Rain"),
    ("تجربه (tajrobe)", "Experience"),
    ("تجارت (tijārat)", "Trade"),
    ("نظریه (nazariye)", "Theory"),
    ("تغییر (taghyīr)", "Change"),
    ("داستان (dāstān)", "Story"),
    ("تفریح (tafrih)", "Recreation"),
    ("هدیه (hedie)", "Gift"),
    ("ساعت (sā'at)", "Clock"),
    ("فرصت (forsat)", "Opportunity"),
    ("حساب (hesāb)", "Account"),
    ("خانه‌ی کودک (khāneh-ye kūdak)", "Kindergarten"),
    ("تصویر (tasvīr)", "Image"),
    ("دستگاه (dastgāh)", "Device"),
    ("جمع‌آوری (jam'āvari)", "Collection"),
    ("آهنگ (āhang)", "Song"),
    ("چراغ (charāgh)", "Lamp"),
    ("پرنده (parande)", "Bird"),
    ("جنگل (jangal)", "Forest"),
    ("کوهستان (kūhestān)", "Mountainous"),
    ("مصرف (masraf)", "Consumption"),
    ("پرورش (parvaresh)", "Raising"),
    ("مصرف‌کننده (masraf konande)", "Consumer"),
    ("پیشنهاد (pishnehād)", "Suggestion"),
    ("تبلیغات (tablighāt)", "Advertising"),
    ("توسعه (tose'e)", "Development"),
    ("خطر (khatr)", "Danger"),
    ("ترس (ters)", "Fear"),
    ("تضاد (tazād)", "Contradiction"),
    ("توانایی (tavānā'ī)", "Ability"),
    ("مجموعه (majmue)", "Collection"),
    ("حیثیت (hesīyat)", "Dignity"),
    ("آزمایش (āzmāyesh)", "Experiment"),
    ("تحقیق (tahqīq)", "Research"),
    ("خدمت (khedmat)", "Service"),
    ("حسن (hasan)", "Beauty"),
    ("رؤیا (ro'yā)", "Vision"),
    ("شجاع (shojā' )", "Brave"),
    ("تاریخچه (tārikhche)", "History"),
    ("تخت (takht)", "Throne"),
    ("درخت (derakht)", "Tree"),
    ("زمین (zamīn)", "Land"),
    ("کشاورزی (keshāvarzī)", "Agriculture"),
    ("صنعت (san'at)", "Industry"),
    ("علم ('elm)", "Science"),
    ("جوان (javān)", "Young"),
    ("پیر (pīr)", "Old"),
    ("روز (rūz)", "Day"),
    ("شب (shab)", "Night"),
    ("فصل (fasl)", "Season"),
    ("زمستان (zemestān)", "Winter"),
    ("بهار (bahār)", "Spring"),
    ("تابستان (tābestān)", "Summer"),
    ("پاییز (pāyiz)", "Autumn"),
    ("خوردن (khordan)", "To eat"),
    ("نوشیدن (noshīdan)", "To drink"),
    ("خوابیدن (khābīdan)", "To sleep"),
    ("دیدن (dīdan)", "To see"),
    ("شنیدن (shenīdan)", "To hear"),
    ("گفتن (goftan)", "To say"),
    ("آموختن (āmūkhtan)", "To learn"),
    ("آمدن (āmadan)", "To come"),
    ("رفتن (raftan)", "To go"),
    ("نویسیدن (nevisīdan)", "To write"),
    ("بخندیدن (bkhandidan)", "To smile"),
    ("گریه کردن (gerye kardan)", "To cry"),
    ("ترسیدن (tarasīdan)", "To fear"),
    ("عشقیدن (eshqīdan)", "To adore"),
    ("رقصیدن (raqsīdan)", "To dance"),
    ("خندیدن (khandidan)", "To laugh"),
    ("پیچیدن (pīchīdan)", "To twist"),
    ("اظهار کردن (ezhār kardan)", "To express"),
    # ... 850 more entries

    # ... (previous entries)

    # Continue with the next batch
    ("دستمال (dastmāl)", "Towel"),
    ("تلویزیون (televīzyon)", "Television"),
    ("صندلی (sandaly)", "Chair"),
    ("میز (mīz)", "Table"),
    ("پنجه (panje)", "Finger"),
    ("پا (pā)", "Leg"),
    ("کت (kat)", "Coat"),
    ("شلوار (shalvār)", "Pants"),
    ("لباس (lebās)", "Clothes"),
    ("کفش (kafsh)", "Shoes"),
    ("ساعت دیواری (sā'at-e dīvārī)", "Wall clock"),
    ("میز کار (mīz-e kār)", "Desk"),
    ("چایخوری (chāykhūrī)", "Teacup"),
    ("قاشق (qāsheq)", "Spoon"),
    ("چاقو (chāghū)", "Knife"),
    ("قاب عکس (qāb-e aks)", "Picture frame"),
    ("کلید (kalīd)", "Key"),
    ("تلفن (telefon)", "Telephone"),
    ("کیف (kīf)", "Bag"),
    ("دستبند (dastband)", "Bracelet"),
    ("شامپو (shāmpū)", "Shampoo"),
    ("حوله (hōleh)", "Towel"),
    ("صابون (sābūn)", "Soap"),
    ("آینه (āyene)", "Mirror"),
    ("پنکه (pankhe)", "Fan"),
    ("پنجره (panjere)", "Window"),
    ("درب (darb)", "Door"),
    ("ساز (sāz)", "Instrument"),
    ("رادیو (rādyo)", "Radio"),
    ("ابزار (ābzār)", "Tool"),
    ("خط (khat)", "Line"),
    ("تابلو (tāblō)", "Painting"),
    ("نظاره (nazāre)", "Observation"),
    ("درخت (derakht)", "Tree"),
    ("گل (gol)", "Flower"),
    ("نقاشی (naqāshī)", "Painting"),
    ("دل (del)", "Heart"),
    ("قلب (ghalb)", "Heart"),
    ("فیلم (film)", "Film"),
    ("آبنبات (ābnabāt)", "Cotton swab"),
    ("گلاب (gelāb)", "Rose"),
    ("ماهی (māhī)", "Fish"),
    ("بشقاب (basqāb)", "Plate"),
    ("دوش (dūsh)", "Shower"),
    ("کتابخانه (ketābkhāneh)", "Library"),
    ("پلیس (polīs)", "Police"),
    ("آب‌نبات (āb-nabāt)", "Watermelon"),
    ("سینه (sīne)", "Chest"),
    ("تخت (takht)", "Bed"),
    ("حمام (hamām)", "Bathroom"),
    ("گوش (gūsh)", "Ear"),
    ("پله (pelle)", "Stairs"),
    ("سالن (sālon)", "Hall"),
    ("لبه (labeh)", "Edge"),
    ("آسمان (āsemān)", "Sky"),
    ("کتاب (ketāb)", "Book"),
    ("خوشحالی (khoshhālī)", "Happiness"),
    ("ماشین (māshīn)", "Car"),
    ("پاییز (pāyiz)", "Autumn"),
    ("آفتاب (āftāb)", "Sun"),
    ("ماه (māh)", "Moon"),
    ("نجمه (nejmeh)", "Star"),
    ("شبنم (shabnam)", "Dew"),
# ... 800 more entries

    # ... (previous entries)

    # ... (previous entries)

    # Continue with the next batch
    ("آبگوشت (ābgūsht)", "Stew"),
    ("چشم (cheshm)", "Eye"),
    ("شیر (shīr)", "Lion"),
    ("گلابی (gelābī)", "Pear"),
    ("تار (tār)", "String"),
    ("بادبان (bādbān)", "Flag"),
    ("آویز (āvīz)", "Hanging"),
    ("آب‌شار (ābshār)", "Waterfall"),
    ("سایه (sāye)", "Shadow"),
    ("مهمان (mehmān)", "Guest"),
    ("دود (dūd)", "Smoke"),
    ("جلیقه (jelīqeh)", "Vest"),
    ("شکلات (shokolāt)", "Chocolate"),
    ("زنگ (zang)", "Bell"),
    ("زنگوله (zangūle)", "Bicycle"),
    ("خنجر (khanjar)", "Dagger"),
    ("عروسی ('arousī)", "Wedding"),
    ("آینه آبگرم (āyene ābgarm)", "Sauna"),
    ("سازمان (sāzmān)", "Organization"),
    ("کارآگاه (kārāgāh)", "Detective"),
    ("تابلو خودرو (tāblū khodrō)", "License plate"),
    ("دستمال کاغذی (dastmāl-e kāghazī)", "Paper towel"),
    ("جلومیز (jolūmīz)", "Tablecloth"),
    ("سفالگری (safālgarī)", "Pottery"),
    ("صابون دست (sābūn-e dast)", "Hand soap"),
    ("تلفن همراه (telefon-e hamrāh)", "Mobile phone"),
    ("گلچین (golchīn)", "Bouquet"),
    ("پنکه سقفی (pankhe-ye saqfī)", "Ceiling fan"),
    ("تلویزیون هوشمند (televīzyon-e hūshmand)", "Smart TV"),
    ("پنجه پا (panje pā)", "Toe"),
    ("باتری (bāterī)", "Battery"),
    ("دستکش (dastkosh)", "Glove"),
    ("دستمال مرطوب (dastmāl-e morṭūb)", "Wet wipes"),
    ("پوشاک (pūshāk)", "Clothing"),
    ("گوشی (gūshī)", "Earphone"),
    ("کلیدواژه (kalīdvāzhe)", "Keyword"),
    ("خرید (kharīd)", "Purchase"),
    ("آسانسور (āsānsor)", "Elevator"),
    ("دلار (dollar)", "Dollar"),
    ("کیلوگرم (kīlogrām)", "Kilogram"),
    ("نمک (namak)", "Salt"),
    ("شیرینی (shīrīnī)", "Sweet"),
    ("شکر (shakar)", "Sugar"),
    ("فلفل (felfel)", "Pepper"),
    ("نان (nān)", "Bread"),
    ("پنجره اتاق (panjere-ye otāq)", "Window of the room"),
    ("هواپیمای جت (havāpeymā-ye jet)", "Jet airplane"),
    ("خوشرو (khoshrew)", "Pleasant"),
    ("آفتاب‌گیر (āftāb-gīr)", "Sunshade"),
    ("بخاری (bokhārī)", "Heater"),
    ("ماهیگیری (māhīgīrī)", "Fishing"),
    ("آسمان‌خراش (āsemān-kharāsh)", "Skydiving"),
    ("میوه خشک (miveh khoshk)", "Dried fruit"),
    ("میوه تازه (miveh tāze)", "Fresh fruit"),
    ("آب‌نبات (āb-nabāt)", "Watermelon"),
    ("لباس تابستانی (lebās-e tābestānī)", "Summer clothes"),
    ("کلاه گردن‌گرم (kolāh gerdan-garm)", "Scarf"),
    ("کمربند (kamarband)", "Belt"),
    ("کفش ورزشی (kafsh-e varzeshī)", "Sports shoes"),
    ("ساعت دیواری (sā'at-e dīvārī)", "Wall clock"),
    ("آینه دست (āyene dast)", "Hand mirror"),
    ("گوشی هوشمند (gūshī hūshmand)", "Smartphone"),
    ("کتابخانه (ketābkhāneh)", "Library"),
    ("کیف دوشی (kīf-e dūshī)", "Backpack"),
    ("سگ (sag)", "Dog"),
    ("گربه (gorbe)", "Cat"),
    ("پرنده (parandeh)", "Bird"),
    ("موش (mūsh)", "Mouse"),
    ("مار (mār)", "Snake"),
    ("میمون (mīmūn)", "Monkey"),
    ("گورخر (gorḵor)", "Donkey"),
    ("اژدها (aždhā)", "Dragon"),
    ("پلنگ (palang)", "Tiger"),
    ("سفید (sefid)", "White"),
    ("سیاه (sīāh)", "Black"),
    ("قرمز (qermez)", "Red"),
    ("آبی (ābī)", "Blue"),
    ("سبز (sabz)", "Green"),
    ("زرد (zard)", "Yellow"),
    ("نارنجی (nārenjī)", "Orange"),
    ("صورتی (sūratī)", "Pink"),
    ("قهوه‌ای (qahve'ī)", "Brown"),
    ("بنفش (banafš)", "Purple"),
    ("خرمایی (khoramā'ī)", "Beige"),
    ("طلایی (talā'ī)", "Gold"),
    ("نقره‌ای (noqre'ī)", "Silver"),
    ("مسی (mesī)", "Copper"),
    ("برنزی (bronzī)", "Bronze"),
    ("پنیر (panīr)", "Cheese"),
    ("شکلات (shokolāt)", "Chocolate"),
    ("پیتزا (pītzā)", "Pizza"),
    ("سوپ (sūp)", "Soup"),
    ("سالاد (sālād)", "Salad"),
    ("برگر (berger)", "Burger"),
    ("نودل (nūdl)", "Noodle"),
    ("پاستا (pāstā)", "Pasta"),
    ("ماست (māst)", "Yogurt"),
    ("آب‌نبات (āb-nabāt)", "Watermelon"),
    ("کلم (kalam)", "Cabbage"),
    ("هویج (havīj)", "Carrot"),
    ("خیار (khīār)", "Cucumber"),
    ("گوجه (goje)", "Tomato"),
    ("پیاز (pyāz)", "Onion"),
    ("سیر (sīr)", "Garlic"),
    ("زنجبیل (zanjebīl)", "Ginger"),
    ("کرفس (kerefes)", "Celery"),
    ("فلفل دلمه‌ای (felfel-e dolmeh'ī)", "Bell pepper"),
    ("خرما (khormā)", "Date"),
    ("انگور (angūr)", "Grape"),
    ("سیب (sīb)", "Apple"),
    ("پرتقال (porteghāl)", "Orange"),
    ("لیمو (līmū)", "Lemon"),
    ("هلو (holū)", "Peach"),
    ("گیلاس (gīlās)", "Cherry"),
    ("توت (tūt)", "Berry"),
    ("تمشک (tūmashk)", "Mulberry"),
    ("انبه (anbāh)", "Mango"),
    ("انجیر (anjīr)", "Fig"),
    ("پرتقال (porteghāl)", "Orange"),
    ("آلو (ālū)", "Plum"),
    ("هندوانه (hendevāneh)", "Watermelon"),
    ("خیابان (khīābān)", "Street"),
    ("کوچه (kūcheh)", "Alley"),
    ("خیابان اصلی (khīābān-e aslī)", "Main street"),
    ("پارک (pārk)", "Park"),
    ("میدان (meidān)", "Square"),
    ("خیابان دیگر (khīābān-e dīgar)", "Another street"),
    ("خیابان فرعی (khīābān-e far'ī)", "Side street"),
    ("خیابان خرید (khīābān-e kharīd)", "Shopping street"),
    ("خیابان مسکونی (khīābān-e maskūnī)", "Residential street"),
    ("خیابان محل کار (khīābān-e mehle kār)", "Workplace street"),
    ("مسجد (masjed)", "Mosque"),
    ("کلیسا (kelīsā)", "Church"),
    ("معبد (ma'bad)", "Temple"),
    ("کاخ (kākh)", "Palace"),
    ("دانشگاه (dāneshgāh)", "University"),
    ("کتابخانه (ketābkhāneh)", "Library"),
    ("بیمارستان (bīmārestān)", "Hospital"),
    ("فروشگاه (forūshgāh)", "Shop"),
    ("رستوران (restorān)", "Restaurant"),
    ("هتل (hotel)", "Hotel"),
    ("کافه (kāfe)", "Café"),
    ("پارکینگ (pārkīng)", "Parking"),
    ("تئاتر (te'āter)", "Theater"),
    ("استخر (estakhr)", "Swimming pool"),
    ("گیم‌سنتر (gīm-sentir)", "Game center"),
    ("استادیوم (ostādīom)", "Stadium"),
    ("مترو (metro)", "Metro"),
    ("اتوبوس (otobus)", "Bus"),
    ("تاکسی (tāksī)", "Taxi"),
    ("تاکسی زرد (tāksī zard)", "Yellow taxi"),
    ("فرودگاه (forūdgāh)", "Airport"),
    ("راه آهن (rāh āhan)", "Railway"),
    ("پل (pol)", "Bridge"),
    ("خانه (khāneh)", "House"),
    ("ویلا (vīlā)", "Villa"),
    ("خانه رستورانی (khāneh restorānī)", "Restaurant house"),


    # ... (previous entries)

    # Continue with the next batch
    ("عالی (ālī)", "Excellent"),
    ("فراموش (faramūsh)", "Forget"),
    ("ترسناک (tarsnāk)", "Scary"),
    ("خنثی (khānithī)", "Neutral"),
    ("شاد (shād)", "Happy"),
    ("ناراضی (nārāzī)", "Unhappy"),
    ("دقیق (daqīq)", "Precise"),
    ("بی‌اعتنا (bī-etnā)", "Careless"),
    ("متشوق (motashawwq)", "Enthusiastic"),
    ("کم‌تر (kamtar)", "Less"),
    ("بیش‌تر (bīshtar)", "More"),
    ("عصبانی (asabānī)", "Angry"),
    ("خوشحال (khoshhāl)", "Content"),
    ("خشن (khoshn)", "Rough"),
    ("نرم (narm)", "Soft"),
    ("تیره (tīre)", "Dark"),
    ("روشن (rowshan)", "Bright"),
    ("مات (māt)", "Checkmate"),
    ("پیروز (pīrūz)", "Victorious"),
    ("دست‌کم (dast-kam)", "At least"),
    ("حداکثر (haddākhtar)", "Maximum"),
    ("حداقل (haddāqal)", "Minimum"),
    ("پیشرفته (pishraftah)", "Advanced"),
    ("ابتدایی (ebtedā'ī)", "Elementary"),
    ("مستقل (mostaghel)", "Independent"),
    ("تابع (tābe' )", "Dependent"),
    ("آزمایشی (āzmāyeshī)", "Experimental"),
    ("استاندارد (estāndārd)", "Standard"),
    ("تازه (tāze)", "Fresh"),
    ("خشک (khoshk)", "Dry"),
    ("تر (tar)", "Wet"),
    ("سرد (sard)", "Cold"),
    ("گرم (garm)", "Warm"),
    ("آتش (ātesh)", "Fire"),
    ("آب (āb)", "Water"),
    ("هوا (havā)", "Air"),
    ("آسمان (āsemān)", "Sky"),
    ("زمین (zamīn)", "Ground"),
    ("دم (dam)", "Breath"),
    ("راه (rāh)", "Way"),
    ("شب (shab)", "Night"),
    ("روز (rūz)", "Day"),
    ("فصل (fasl)", "Season"),
    ("خوراک (khōrāk)", "Food"),
    ("نوشیدنی (noshīdani)", "Beverage"),
    ("شیر (shīr)", "Milk"),
    ("چای (chāy)", "Tea"),
    ("قهوه (ghahveh)", "Coffee"),
    ("شکلات (shokolāt)", "Chocolate"),
    ("میوه (miveh)", "Fruit"),
    ("سبزی (sabzi)", "Vegetable"),
    ("نان (nān)", "Bread"),
    ("خوراکی (khōrākī)", "Snack"),
    ("غذا (ghazā)", "Meal"),
    ("ناهار (nāhār)", "Lunch"),
    ("شام (shām)", "Dinner"),
    ("صبحانه (sobhāneh)", "Breakfast"),
# ... 750 more entries


# ... (previous entries)

# Continue with the next batch
("پیاده‌روی (piyāde-ravī)", "Walk"),
("دویدن (dūīdan)", "Run"),
("دوچرخه‌سواری (dūcharkheh-savārī)", "Bicycling"),
("شنا (shenā)", "Swimming"),
("پرواز (parvāz)", "Flight"),
("رانندگی (rānandegī)", "Driving"),
("قطار (qatār)", "Train"),
("اتوبوس (otobūs)", "Bus"),
("مترو (metro)", "Metro"),
("تاکسی (tāksī)", "Taxi"),
("ماشین (māshīn)", "Car"),
("موتور (mūtor)", "Motorcycle"),
("قایق (qāyeq)", "Boat"),
("هواپیما (havāpeymā)", "Airplane"),
("دریاچه (daryāche)", "Lake"),
("دریا (daryā)", "Sea"),
("رودخانه (rūdkhāneh)", "River"),
("کوه (kūh)", "Mountain"),
("کویر (kavīr)", "Desert"),
("جنگل (jangal)", "Forest"),
("میدان (meydān)", "Square"),
("پارک (pārk)", "Park"),
("شهر (shahr)", "City"),
("روستا (rūstā)", "Village"),
("منطقه (mantaghe)", "Region"),
("کشور (keshvar)", "Country"),
("قاره (qārāh)", "Continent"),
("زمینه (zamīneh)", "Field"),
("صنعت (san'at)", "Industry"),
("کشاورزی (keshāvarzī)", "Agriculture"),
("معدن (ma'dan)", "Mine"),
("دانشگاه (dāneshgāh)", "University"),
("مدرسه (madrese)", "School"),
("کلاس (kelās)", "Class"),
("استاد (ostād)", "Teacher"),
("دانش‌آموز (dāneshāmūz)", "Student"),
("دفتر (daftar)", "Office"),
("کارخانه (kārkhāneh)", "Factory"),
("بیمارستان (bīmārestān)", "Hospital"),
("فروشگاه (forūshgāh)", "Store"),
("رستوران (restorān)", "Restaurant"),
("کافه (kāfe)", "Café"),
("پارو (pāro)", "Sail"),
("پنجه (panje)", "Fin"),
("صورت (sūrat)", "Face"),
("مو (mū)", "Hair"),
("چشم (chashm)", "Eye"),
("گوش (gūsh)", "Ear"),
("لب (lab)", "Lip"),
("دندان (dandān)", "Tooth"),
("دهان (dahān)", "Mouth"),
("زبان (zabān)", "Tongue"),
("گردن (gordan)", "Neck"),
("شانه (shāneh)", "Shoulder"),
("بازو (bāzū)", "Arm"),
("دست (dast)", "Hand"),
("پنجه دست (panje-ye dast)", "Finger"),
("ناخن (nākhun)", "Nail"),
("پا (pā)", "Leg"),
("زانو (zānu)", "Knee"),
("پاچه (pāche)", "Ankle"),
("پاشنه (pāshne)", "Heel"),
("ابتدای پا (ebtedā-ye pā)", "Toe"),
("پوست (pūst)", "Skin"),
# ... 700 more entries


# ... (previous entries)

# Continue with the next batch
("قلب (ghalb)", "Heart"),
("کبد (kabed)", "Liver"),
("ریه (reyh)", "Lung"),
("معده (ma'deh)", "Stomach"),
("روده (rūdeh)", "Intestine"),
("مغز (maghz)", "Brain"),
("عضله (azle)", "Muscle"),
("خواب (khāb)", "Dream"),
("پنجره (panjere)", "Window"),
("دروازه (darvāze)", "Door"),
("سقف (saqf)", "Ceiling"),
("دیوار (dīvār)", "Wall"),
("کف (kaf)", "Floor"),
("پله (pelle)", "Stairs"),
("سقوف (soqūf)", "Roof"),
("میز (mīz)", "Table"),
("صندلی (sandaly)", "Chair"),
("تخت (takht)", "Bed"),
("کمد (kamod)", "Closet"),
("آینه (āyene)", "Mirror"),
("قاب عکس (qāb-e aks)", "Picture frame"),
("چراغ (charāgh)", "Lamp"),
("فرش (farsh)", "Carpet"),
("پنجه (panje)", "Finger"),
("ناخن (nākhun)", "Nail"),
("مو (mū)", "Hair"),
("کفش (kafsh)", "Shoes"),
("شلوار (shalvār)", "Pants"),
("کت (kat)", "Coat"),
("پیراهن (pīrāhan)", "Shirt"),
("کلاه (kolāh)", "Hat"),
("دستکش (dastgosh)", "Glove"),
("لباس (lebās)", "Clothes"),
("ساعت (sā'at)", "Watch"),
("گوشواره (gūshvāre)", "Earring"),
("گردنبند (gordanband)", "Necklace"),
("حلقه (halqeh)", "Ring"),
("دستبند (dastband)", "Bracelet"),
("مهر (mohr)", "Ring (seal)"),
("نظاره (nazāre)", "Observation"),
("پلکان (pelkān)", "Escalator"),
("آسانسور (āsānsor)", "Elevator"),
("پنجره‌ی سازمانی (panjere-ye sāzmānī)", "Organizational window"),
("سنگ (sang)", "Stone"),
("خاک (khāk)", "Dirt"),
("آسمان (āsemān)", "Sky"),
("ابر (abr)", "Cloud"),
("باد (bād)", "Wind"),
("باران (bārān)", "Rain"),
("برف (barf)", "Snow"),
("گل (gol)", "Flower"),
("درخت (derakht)", "Tree"),
("مرغ (morgh)", "Bird"),
("پرنده (parande)", "Bird"),
("پرواز (parvāz)", "Flight"),
("آب (āb)", "Water"),
("دریا (daryā)", "Sea"),
("رود (rūd)", "River"),
("جزیره (jazire)", "Island"),
("شن (shen)", "Sand"),
("آتش (ātesh)", "Fire"),
("گرما (garmā)", "Heat"),
# ... 650 more entries

# ... (previous entries)

# Continue with the next batch
("با (bā)", "With"),
("بدون (bedūn)", "Without"),
("برای (barāy)", "For"),
("از (az)", "From"),
("تا (tā)", "Until"),
("تو (to)", "In"),
("روی (rūy)", "On"),
("در (dar)", "At"),
("زیر (zīr)", "Under"),
("بالا (bālā)", "Above"),
("پایین (pāyīn)", "Below"),
("پشت (posht)", "Behind"),
("جلو (jolo)", "In front of"),
("کنار (kenār)", "Beside"),
("بین (bīn)", "Between"),
("جلوی (jelooye)", "In front of"),
("داخل (dākhel)", "Inside"),
("خارج (khārej)", "Outside"),
("دیگر (dīgar)", "Other"),
("همیشه (hamīshe)", "Always"),
("همه (hame)", "All"),
("همین (hamīn)", "This"),
("همان (hamān)", "That"),
("اینجا (īnjā)", "Here"),
("آنجا (ānjā)", "There"),
("زود (zūd)", "Soon"),
("حالا (hālā)", "Now"),
("هنوز (hanoz)", "Still"),
("تازه (tāze)", "Fresh"),
("هرگز (hargez)", "Never"),
("شاید (shāyad)", "Maybe"),
("البته (albateh)", "Of course"),
("الان (ālān)", "Right now"),
("تقریبا (taqrīban)", "Approximately"),
("حتما (hatman)", "Definitely"),
("آره (āre)", "Yes"),
("نه (na)", "No"),
("لطفا (lotfan)", "Please"),
("ممنون (mamnūn)", "Thank you"),
("خوب (khūb)", "Good"),
("بد (bad)", "Bad"),
("زیبا (zībā)", "Beautiful"),
("قدرتی (qodratī)", "Powerful"),
("ضعیف (za'īf)", "Weak"),
("شگفت‌انگیز (shogofte-angīz)", "Amazing"),
("عجیب (ajīb)", "Strange"),
("کوچک (kūchak)", "Small"),
("بزرگ (bozorg)", "Big"),
("جدید (jadīd)", "New"),
("قدیمی (qadīmī)", "Old"),
("بلند (boland)", "Tall"),
("کوتاه (kūtāh)", "Short"),
("خوش (khosh)", "Well"),
("بد (bad)", "Bad"),
("چرا (chera)", "Why"),
("چطور (chetor)", "How"),
("کجا (kojā)", "Where"),
("کی (kī)", "When"),
("چه (che)", "What"),
("چند (chand)", "How many"),
("چه‌قدر (che qadr)", "How much"),
("آیا (āyā)", "Is it"),
("هر (har)", "Each"),
("هیچ (hīch)", "None"),
("تمام (tamām)", "Complete"),
("ناقص (nāqes)", "Incomplete"),
("دیروقت (dirūqat)", "Early"),
("دیر (dir)", "Late"),
("فورا (forā)", "Immediately"),
("گاهی (gāhī)", "Sometimes"),
("پیش (pīsh)", "Before"),
("بعد (ba'd)", "After"),
("بیرون (bīrūn)", "Outside"),
("داخل (dākhel)", "Inside"),
("دست (dast)", "Hand"),
("پا (pā)", "Leg"),
("پنجه (panje)", "Finger"),
("آن (ān)", "That"),
("این (īn)", "This"),
("آنجا (ānjā)", "There"),
("اینجا (īnjā)", "Here"),
# ... 550 more entries

# ... (previous entries)

# Continue with the next batch
("آهنگ (āhang)", "Song"),
("فیلم (film)", "Movie"),
("کتاب (ketāb)", "Book"),
("نقاشی (naqāshī)", "Painting"),
("شعر (she'r)", "Poetry"),
("خنده (khandeh)", "Laughter"),
("گریه (geryeh)", "Crying"),
("کلید (kelīd)", "Key"),
("قفل (ghofl)", "Lock"),
("پنجره (panjere)", "Window"),
("دروازه (darvāze)", "Door"),
("سقف (saqf)", "Ceiling"),
("دیوار (dīvār)", "Wall"),
("کف (kaf)", "Floor"),
("پله (pelle)", "Stairs"),
("سقوف (soqūf)", "Roof"),
("میز (mīz)", "Table"),
("صندلی (sandaly)", "Chair"),
("تخت (takht)", "Bed"),
("کمد (kamod)", "Closet"),
("آینه (āyene)", "Mirror"),
("قاب عکس (qāb-e aks)", "Picture frame"),
("چراغ (charāgh)", "Lamp"),
("فرش (farsh)", "Carpet"),
("کیف (kīf)", "Bag"),
("کیف پول (kīf-e pūl)", "Wallet"),
("تلفن (telefon)", "Telephone"),
("لپ‌تاپ (laptop)", "Laptop"),
("ماشین حساب (māshīn-e hasāb)", "Calculator"),
("قلم (qalam)", "Pen"),
("مداد (medād)", "Pencil"),
("کاغذ (kāghaz)", "Paper"),
("خودکار (khodkār)", "Ballpoint pen"),
("مسواک (meswāk)", "Toothbrush"),
("خمیر دندان (khamīr-e dandān)", "Toothpaste"),
("شامپو (shāmpū)", "Shampoo"),
("صابون (sābūn)", "Soap"),
("حوله (ḥolh)", "Towel"),
("قهوه (ghahveh)", "Coffee"),
("چای (chāy)", "Tea"),
("نوشیدنی (noshīdani)", "Beverage"),
("سیب (sib)", "Apple"),
("پرتقال (porteghāl)", "Orange"),
("موز (mūz)", "Banana"),
("انگور (angūr)", "Grape"),
("آب‌نبات (ābnabāt)", "Plant"),
("گل (gol)", "Flower"),
("شجره (shajare)", "Tree"),
("نجفه (nojeh)", "Star"),
("قمر (qamar)", "Moon"),
("آفتاب (āftāb)", "Sun"),
("ابر (abr)", "Cloud"),
("باد (bād)", "Wind"),
("باران (bārān)", "Rain"),
("برف (barf)", "Snow"),
("خوراک (khōrāk)", "Food"),
("نوشیدنی (noshīdani)", "Beverage"),
("شیر (shīr)", "Milk"),
("چای (chāy)", "Tea"),
("قهوه (ghahveh)", "Coffee"),
("شکلات (shokolāt)", "Chocolate"),
("میوه (miveh)", "Fruit"),
("سبزی (sabzi)", "Vegetable"),
("نان (nān)", "Bread"),
("خوراکی (khōrākī)", "Snack"),
("غذا (ghazā)", "Meal"),
("ناهار (nāhār)", "Lunch"),
("شام (shām)", "Dinner"),
("صبحانه (sobhāneh)", "Breakfast"),
("فنجان (fenjān)", "Cup"),
("ظرف (zārf)", "Container"),
("طبقه (tabaq)", "Plate"),
("قاشق (qāsheq)", "Spoon"),
("چنگال (changāl)", "Fork"),
("کارد (kārd)", "Knife"),
("قابلمه (qābelame)", "Pot"),
("ماهیتابه (māhītābe)", "Pan"),
("کاسه (kāse)", "Bowl"),
("دسته (daste)", "Set"),
("نظافت (nezāfat)", "Cleanliness"),
("خرید (kharīd)", "Purchase"),
("پرداخت (pardākhth)", "Payment"),
("مخصوص (mokhassas)", "Special"),
("عادی (‘ādī)", "Regular"),
("نو (nav)", "New"),
("قدیمی (qadīmī)", "Old"),
("خوب (khūb)", "Good"),
("بد (bad)", "Bad"),
("آزاد (āzād)", "Free"),
("محدود (mahdūd)", "Limited"),
("شلوغ (sholoogh)", "Busy"),
("آرام (ārām)", "Calm"),
("باشگاه (bāshgāh)", "Club"),
("رستوران (restorān)", "Restaurant"),
("کافه (kāfe)", "Café"),
("پارک (pārk)", "Park"),
("تالار (tālār)", "Hall"),
("سینما (sīnemā)", "Cinema"),
("تئاتر (te'āter)", "Theater"),
("موزه (moze)", "Museum"),
("کتابخانه (ketābkhāneh)", "Library"),
("آموزشگاه (āmūzeshgāh)", "School"),
("دانشگاه (dāneshgāh)", "University"),
("استاد (ostād)", "Teacher"),
("دانش‌آموز (dāneshāmūz)", "Student"),
("آموزش (āmūzesh)", "Education"),
("پزشک (pezeshk)", "Doctor"),
("دارو (dāro)", "Medicine"),
("بیمار (bīmār)", "Patient"),
("درمان (darmān)", "Treatment"),
("پرستار (parastār)", "Nurse"),
("پزشکی (pezeshkī)", "Medical"),
("مهندس (mohandes)", "Engineer"),
("کشاورزی (keshāvarzī)", "Agriculture"),
("صنعت (san'at)", "Industry"),
("فناوری (fenāvverī)", "Technology"),
("رایانه (rāyāneh)", "Computer"),
("شبکه (shabake)", "Network"),
("تلویزیون (televīzyon)", "Television"),
("رادیو (rādīo)", "Radio"),
("اخبار (akhbār)", "News"),
("ورزش (varzesh)", "Sport"),
("فوتبال (fūtbāl)", "Football"),
("بسکتبال (basketbāl)", "Basketball"),
("والیبال (vālībāl)", "Volleyball"),
("دوچرخه (dūcharkhe)", "Bicycle"),
("دویدن (dūīdan)", "Run"),
("شنا (shenā)", "Swimming"),
("پیاده‌روی (piyāde-ravī)", "Walk"),
("موزیک (mūzīk)", "Music"),
("نقاشی (naqāshī)", "Painting"),
("تئاتر (te'āter)", "Theater"),
("فیلم (film)", "Movie"),
("عکس (aks)", "Photo"),
("شعر (she'r)", "Poetry"),
("کتاب (ketāb)", "Book"),
("رمان (romān)", "Novel"),
("مجله (majale)", "Magazine"),
("خبر (khabar)", "News"),
("راست (rāst)", "Right"),
("چپ (chap)", "Left"),
("پیش (pīsh)", "Forward"),
("عقب (aqb)", "Backward"),
("بالا (bālā)", "Up"),
("پایین (pāyīn)", "Down"),
("نزدیک (nazdīk)", "Near"),
("دور (dūr)", "Far"),
("داخل (dākhel)", "Inside"),
("برخوردار (barxodār)", "Available"),
("خالی (khālī)", "Empty"),
("پر (por)", "Full"),
("جلو (jolo)", "In front of"),
("پشت (posht)", "Behind"),
("بین (bīn)", "Between"),
("جلوی (jelooye)", "In front of"),
("زیر (zīr)", "Under"),
("روی (rūy)", "On"),
("در (dar)", "At"),
("تو (to)", "In"),
("برای (barāy)", "For"),
("بدون (bedūn)", "Without"),
("در مورد (dar mowrde)", "About"),
("تا (tā)", "Until"),
("با (bā)", "With"),
("از (az)", "From"),
# ... 400 more entries


    ("زیبا (zībā)", "Beautiful"),
    ("خوب (khūb)", "Good"),
    ("بد (bad)", "Bad"),
    ("زیاد (ziyād)", "Much"),
    ("کم (kam)", "Few"),
    ("زود (zūd)", "Fast"),
    ("آهسته (āhesteh)", "Slow"),
    ("بالا (bālā)", "High"),
    ("پایین (pāyīn)", "Low"),
    ("دقیقا (daqīqā)", "Exactly"),
    ("تقریبا (taqrīban)", "Almost"),
    ("همیشه (hamīshe)", "Always"),
    ("هرگز (hargez)", "Never"),
    ("خوب (khūb)", "Well"),
    ("بد (bad)", "Bad"),
    ("بله (bale)", "Yes"),
    ("نه (na)", "No"),
    ("البته (albateh)", "Of course"),
    ("فورا (forā)", "Immediately"),
    ("ممکن (momken)", "Possible"),
    ("محال (ma'mūl)", "Impossible"),
    ("آرام (ārām)", "Calm"),
    ("پر (por)", "Full"),
    ("خالی (khālī)", "Empty"),
    ("بیرون (bīrūn)", "Outside"),
    ("داخل (dākhel)", "Inside"),
    ("بهترین (behtarin)", "Best"),
    ("بدترین (badtarin)", "Worst"),
    ("زودتر (zūdtar)", "Sooner"),
    ("دیرتر (dirter)", "Later"),
    ("خوبتر (khūbtar)", "Better"),
    ("بدتر (badtar)", "Worse"),
    ("آرامتر (ārāmtar)", "More calmly"),
    ("سریعتر (sor'atar)", "Faster"),
    ("آسان‌تر (āsāntar)", "Easier"),
    ("سخت‌تر (sakhtar)", "Harder"),
    ("خوشحال (khoshhāl)", "Happy"),
    ("ناراحت (nārāhat)", "Unhappy"),
    ("خوب‌ترین (khūbtarin)", "The best"),
    ("بدترین (badtarin)", "The worst"),
    ("زیباترین (zībatarin)", "The most beautiful"),
    ("بدترین (badtarin)", "The least beautiful"),
    ("بسیار (besyār)", "Very"),
    ("تقریبا (taqrīban)", "Almost"),
    ("خیلی (khīlī)", "Very"),
    ("کمی (kamī)", "A little"),
    ("خوب (khūb)", "Fine"),
    ("ضعیف (za'īf)", "Weak"),
    ("قوی (qavī)", "Strong"),
    ("دائما (dā'ema)", "Always"),
    ("ابدا (abadā)", "Never"),
    ("بخوبی (bekhūbī)", "Well"),
    ("بدون شک (bedūn shak)", "Without a doubt"),
    ("بهترین (behtarin)", "Best"),
    ("عجیب (ajīb)", "Strange"),
    ("عجیب‌تر (ajībtar)", "Stranger"),
    ("عجیب‌ترین (ajībtarīn)", "The strangest"),
    ("دقیق (daqīq)", "Exactly"),
    ("آرام (ārām)", "Calm"),
    ("پر (por)", "Full"),
    ("خالی (khālī)", "Empty"),
    ("بیرون (bīrūn)", "Outside"),
    ("داخل (dākhel)", "Inside"),
    ("قدیمی (qadīmī)", "Old"),
    ("جدید (jadīd)", "New"),
    ("بزرگ (bozorg)", "Big"),
    ("کوچک (kūchak)", "Small"),
    ("زیاد (ziyād)", "Much"),
    ("کم (kam)", "Few"),
    ("آهسته (āhesteh)", "Slow"),
    ("سریع (sor'ī)", "Fast"),
    ("آنجا (ānjā)", "There"),
    ("اینجا (īnjā)", "Here"),
    ("هنوز (hanoz)", "Still"),
    ("تازه (tāze)", "Fresh"),
    ("آن (ān)", "That"),
    ("این (īn)", "This"),
    ("آنجا (ānjā)", "There"),
    ("اینجا (īnjā)", "Here"),
    ("همیشه (hamīshe)", "Always"),
    ("هرگز (hargez)", "Never"),
    ("سریعا (sor'īā)", "Quickly"),
    ("کاملا (kāmelā)", "Completely"),
    ("تقریبا (taqrīban)", "Almost"),
    ("حتما (hatman)", "Definitely"),
    ("باز (bāz)", "Again"),
    ("یکجا (yekjā)", "Together"),
    ("جدا (jodā)", "Apart"),
    ("به‌زودی (be-zūdī)", "Soon"),
    ("همزمان (hamzamān)", "Simultaneously"),
    ("گاهی (gāhī)", "Sometimes"),
    ("رفته رفته (rafta rafta)", "Gradually"),
    ("آهسته آهسته (āhesteh āhesteh)", "Slowly, slowly"),
    ("همواره (hamvāre)", "Constantly"),
    ("بلافاصله (belā-fāsele)", "Immediately"),
    ("قبلا (qablā)", "Previously"),
    ("حالا (hālā)", "Now"),
    ("زودتر (zūdtar)", "Sooner"),
    ("دیرتر (dirter)", "Later"),
    ("خوشحالانه (khoshhālāneh)", "Happily"),
    ("متاسفانه (motāsefāneh)", "Unfortunately"),
    ("شاید (shayad)", "Maybe"),
    ("البته (albateh)", "Of course"),
    ("احتمالا (ehtemālā)", "Probably"),
    ("به زودی (be zūdī)", "Soon"),
    ("با خوشحالی (bā khoshhālī)", "Happily"),
    ("با ناراحتی (bā nārāhatī)", "Unhappily"),
    ("خوب (khūb)", "Well"),
    ("برخوردار (barxodār)", "Available"),
    ("پر (por)", "Full"),
    ("خالی (khālī)", "Empty"),
    ("به تدریج (be tadrīj)", "Gradually"),
    ("با احتیاط (bā ehtiyāt)", "With caution"),
    ("با عجله (bā ajle)", "Hurriedly"),
    ("با آرامش (bā ārāmesh)", "Calmly"),
    ("با شوق (bā šoq)", "Eagerly"),
    ("با آرامی (bā ārāmī)", "With ease"),
    ("با تمام وجود (bā tamām vajūd)", "With all one's heart"),
    ("به آرامی (be ārāmī)", "Slowly"),
    ("به سرعت (be sor'at)", "Quickly"),
    ("به دقت (be daqat)", "Carefully"),
    ("به سختی (be sakhtī)", "With difficulty"),
    ("به راحتی (be rāhatī)", "Easily"),
    ("به تدریج (be tadrīj)", "Gradually"),
    ("به آرامی (be ārāmī)", "With ease"),
    ("به شدت (be šaddat)", "Intensely"),
    ("به زودی (be zūdī)", "Soon"),
    ("به سرعت (be sor'at)", "Quickly"),
    ("به آسانی (be āsānī)", "Effortlessly"),
    ("به‌طور کلی (be-tor-e kollī)", "Generally"),
    ("به وضوح (be vazūh)", "Clearly"),
    ("به احتمال زیاد (be ehtemāl-e ziyād)", "Most likely"),
    ("به ندرت (be nadrat)", "Rarely"),
    ("به نظر می‌آید (be nazar mi-āyad)", "It seems"),
    ("به شدت (be šaddat)", "Severely"),
    ("به‌طور کامل (be-tor-e kāmel)", "Completely"),
    ("به‌صورت رسمی (be-sūrat-e rasmi)", "Formally"),
    ("به‌طور غیررسمی (be-tor-e gheyr-rasmi)", "Informally"),
    ("به‌طور معمول (be-tor-e ma'mūl)", "Usually"),
    ("به‌طور واضح (be-tor-e vāzeh)", "Clearly"),
    ("به‌طور کلی (be-tor-e kollī)", "Generally"),
    ("به‌صورت کلی (be-sūrat-e kollī)", "Overall"),
    ("به‌طور خودکار (be-tor-e khod-kār)", "Automatically"),
    ("به‌طور خودکار (be-tor-e khod-kār)", "By itself"),
    ("به‌طور گسترده (be-tor-e gostarde)", "Extensively"),
    ("به‌طور معمول (be-tor-e ma'mūl)", "Usually"),
    ("به‌طور مشخص (be-tor-e moshtagh)", "Clearly"),
    ("به‌طور معمول (be-tor-e ma'mūl)", "Normally"),
    ("به‌طور فوری (be-tor-e forī)", "Immediately"),
    ("به‌طور زود (be-tor-e zūd)", "Quickly"),
    ("به‌طور یکسان (be-tor-e yeksān)", "Uniformly"),
    ("به‌طور یکجا (be-tor-e yekjā)", "Together"),
    ("به‌طور همزمان (be-tor-e hamzamān)", "Simultaneously"),
    ("به‌طور ناگهانی (be-tor-e nāgehānī)", "Suddenly"),
    ("به‌طور آرام (be-tor-e ārām)", "Slowly"),
    ("به‌طور فوری (be-tor-e forī)", "Instantly"),
    ("به‌طور همزمان (be-tor-e hamzamān)", "Concurrently"),
    ("به‌طور خوب (be-tor-e khūb)", "Well"),
    ("به‌طور نادرست (be-tor-e nādorost)", "Incorrectly"),
    ("به‌طور کلی (be-tor-e kollī)", "On the whole"),
    ("به‌طور مستقیم (be-tor-e mostaqīm)", "Directly"),
    ("به‌طور عمدتا (be-tor-e omdatā)", "Mainly"),


    # ... (previous entries)

# Continue with the next batch
("زیبا (zībā)", "Beautiful"),
("سریع (serī'", "Fast"),
("آهسته (āhesteh)", "Slow"),
("سنگین (sangīn)", "Heavy"),
("سبک (sabok)", "Light"),
("سخت (sakht)", "Hard"),
("نرم (narm)", "Soft"),
("زنده (zendeh)", "Alive"),
("مرده (murda)", "Dead"),
("قدیمی (qadīmī)", "Old"),
("جدید (jadīd)", "New"),
("پاره (pāre)", "Broken"),
("سالم (sālem)", "Healthy"),
("بی‌رحم (bī-raḥm)", "Merciless"),
("مهربان (mehrābān)", "Kind"),
("خوشحال (khoshhāl)", "Happy"),
("غمگین (ghamgīn)", "Sad"),
("ترسیده (tarasīde)", "Afraid"),
("خسته (khaste)", "Tired"),
("پرانرژی (por enérzhī)", "Energetic"),
("خوب (khūb)", "Good"),
("بد (bad)", "Bad"),
("بلند (boland)", "Tall"),
("کوتاه (kūtāh)", "Short"),
("دقیق (daqīq)", "Precise"),
("کلی (kolī)", "Total"),
("جزئی (jazā'ī)", "Partial"),
("درست (dorost)", "Correct"),
("غلط (ghalat)", "Incorrect"),
("سخت (sakht)", "Difficult"),
("آسان (āsān)", "Easy"),
("زیاد (ziyād)", "Many"),
("کم (kam)", "Few"),
("برفی (barfī)", "Snowy"),
("بارانی (bārānī)", "Rainy"),
("داغ (dāgh)", "Hot"),
("سرد (sard)", "Cold"),
("پر (por)", "Full"),
("خالی (khālī)", "Empty"),
("صاف (ṣāf)", "Smooth"),
("خشن (khoshn)", "Rough"),
("نرم (narm)", "Soft"),
("خشک (khoshk)", "Dry"),
("تر (tar)", "Wet"),
("پرسشی (pershī)", "Curious"),
("بی‌تفاوت (bī-tafāvot)", "Indifferent"),
("مستقیم (mostaqīm)", "Straight"),
("چرب (charb)", "Greasy"),
("سفت (saft)", "Firm"),
("سبز (sabz)", "Green"),
("زرد (zard)", "Yellow"),
("آبی (ābī)", "Blue"),
("قرمز (qermez)", "Red"),
("سیاه (sīāh)", "Black"),
("سفید (safīd)", "White"),
("صورتی (sūretī)", "Pink"),
("پریده (parīde)", "Jumped"),
("دویده (davīde)", "Ran"),
("آهسته (āhesteh)", "Slow"),
("سریع (serī'", "Fast"),
("زیبا (zībā)", "Beautiful"),
("قشنگ (qashang)", "Pretty"),
("قبله (qeble)", "Ugly"),
("کوچک (kūchak)", "Small"),
("بزرگ (bozorg)", "Big"),
("لاغر (lāghar)", "Slim"),
("چاق (chāq)", "Chubby"),
("پر (por)", "Full"),
("خالی (khālī)", "Empty"),
("پنجره‌ای (panjere'ī)", "Windowy"),
("دروازه‌ای (darvāze'ī)", "Doory"),
("سقفی (saqfī)", "Ceilingy"),
("دیواری (dīvārī)", "Wally"),
("زمینی (zemīnī)", "Groundy"),
("آسمانی (āsemānī)", "Skyish"),
("گرم (garm)", "Warm"),
("سرد (sard)", "Cold"),
("خنک (khonak)", "Cool"),
("سریعا (serī'a)", "Quickly"),
("آهسته (āhesteh)", "Slowly"),
("زیاد (ziyād)", "Much/More"),
("کم (kam)", "Few/Less"),
("همیشه (hamīshe)", "Always"),
("هرگز (hargez)", "Never"),
("ممکن (momken)", "Possible"),
("ناممکن (nāmomken)", "Impossible"),
("مستقیما (mostaqīmā)", "Directly"),
("غیرمستقیما (ghayremostaqīmā)", "Indirectly"),
("فورا (forā)", "Immediately"),
("به‌تدریج (be tadrīj)", "Gradually"),
("قطعا (qat'an)", "Certainly"),
("شاید (shāyad)", "Perhaps"),
("اصولا (osūla)", "Generally"),
("به‌صورت (be sūrat)", "Formally"),
("به‌طور (be tūr)", "Informally")

]


# unique_word_data = list(set(map(tuple, word_data)))

random.shuffle(word_data)


# Create a CSV file and write the data
with open('anki_word_list.csv', mode='w', encoding='utf-8', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Word 1", "Word 2"])
    for word_data_entry in word_data:
        persian_word, english_word = word_data_entry
        # writer.writerow([f"{english_word}" , f"{persian_word}"])
        writer.writerow([f"{persian_word}" , f"{english_word}"])

        #writer.writerow([f"{tense}", translation])

print("Anki-compatible CSV file with verbs created successfully!")
