import csv


verb_data = [
    ("رقصیدن", "رقص می‌کنم (present)", "To dance", "raqsidan", "raqs mikonam  "),
    ("رقصیدن", "رقصیدم (past)", "To dance", "raqsidan", "raqsidam  "),
    ("عشقیدن", "عشق می‌کنم (present)", "To adore", "eshqidan", "eshq mikonam  "),
    ("عشقیدن", "عشقیدم (past)", "To adore", "eshqidan", "eshqidam  "),
    ("مسافرت کردن", "مسافرت می‌کنم (present)", "To travel", "mosaferat kardan", "mosaferat mikonam  "),
    ("مسافرت کردن", "مسافرت کردم (past)", "To travel", "mosaferat kardan", "mosaferat kardam  "),
    ("معاف کردن", "معاف می‌کنم (present)", "To forgive", "ma'af kardan", "ma'af mikonam  "),
    ("معاف کردن", "معاف کردم (past)", "To forgive", "ma'af kardan", "ma'af kardam  "),
    ("دست زدن", "دست می‌زنم (present)", "To applaud", "dast zadan", "dast mizanam  "),
    ("دست زدن", "دست زدم (past)", "To applaud", "dast zadan", "dast zadam  "),
    ("ترسیدن", "ترس می‌کنم (present)", "To fear", "tarasidan", "taras mikonam  "),
    ("ترسیدن", "ترسیدم (past)", "To fear", "tarasidan", "tarasidam  "),
    ("تغییر دادن", "تغییر می‌دهم (present)", "To change", "taghir dadan", "taghir mideham  "),
    ("تغییر دادن", "تغییر دادم (past)", "To change", "taghir dadan", "taghir dadam  "),
    ("مسابقه کردن", "مسابقه می‌کنم (present)", "To compete", "mosabeghe kardan", "mosabeghe mikonam  "),
    ("مسابقه کردن", "مسابقه کردم (past)", "To compete", "mosabeghe kardan", "mosabeghe kardam  "),
    ("پیچیدن", "پیچ می‌کنم (present)", "To twist", "pichidan", "pich mikonam  "),
    ("پیچیدن", "پیچیدم (past)", "To twist", "pichidan", "pichidam  "),
    ("اظهار کردن", "اظهار می‌کنم (present)", "To express", "ezhare kardan", "ezhare mikonam  "),
    ("اظهار کردن", "اظهار کردم (past)", "To express", "ezhare kardan", "ezhare kardam  "),
    ("خوردن", "می‌خورم (present)", "To eat", "khordan", "mikhoram  "),
    ("خوردن", "خوردم (past)", "To eat", "khordan", "khordam  "),
    ("خوابیدن", "می‌خوابم (present)", "To sleep", "khobidan", "mikhobam  "),
    ("خوابیدن", "خوابیدم (past)", "To sleep", "khobidan", "khobidam  "),
    ("گریه کردن", "می‌گریم (present)", "To cry", "gerye kardan", "migiram  "),
    ("گریه کردن", "گریه کردم (past)", "To cry", "gerye kardan", "gerye kardam  "),
    ("خندیدن", "می‌خندم (present)", "To laugh", "khandidan", "mikhandidam  "),
    ("خندیدن", "خندیدم (past)", "To laugh", "khandidan", "khandidam  "),
    ("گفتن", "می‌گویم (present)", "To say", "goftan", "migooyam  "),
    ("گفتن", "گفتم (past)", "To say", "goftan", "goftam  "),
    ("نوشتن", "می‌نویسم (present)", "To write", "neveshtan", "minevisam  "),
    ("نوشتن", "نوشتم (past)", "To write", "neveshtan", "neveshtam  "),
    ("پرواز کردن", "پرواز می‌کنم (present)", "To fly", "parvaz kardan", "parvaz mikonam  "),
    ("پرواز کردن", "پرواز کردم (past)", "To fly", "parvaz kardan", "parvaz kardam  "),
    ("شنیدن", "می‌شنوم (present)", "To hear", "shenidan", "mishenavam  "),
    ("شنیدن", "شنیدم (past)", "To hear", "shenidan", "shenidam  "),
    ("دیدن", "می‌بینم (present)", "To see", "didan", "mibinam  "),
    ("دیدن", "دیدم (past)", "To see", "didan", "didam  "),
    ("پریدن", "می‌پرم (present)", "To jump", "paridan", "miparam  "),
    ("پریدن", "پریدم (past)", "To jump", "paridan", "paridam  "),
    ("دویدن", "می‌دوم (present)", "To run", "davidan", "midavam  "),
    ("دویدن", "دویدم (past)", "To run", "davidan", "davidam  "),
    ("کردن", "می‌کنم (present)", "To do", "kardan", "mikonam  "),
    ("کردن", "کردم (past)", "To do", "kardan", "kardam  "),
    ("ماندن", "می‌مانم (present)", "To stay", "mandan", "mimananam  "),
    ("ماندن", "ماندم (past)", "To stay", "mandan", "mandam  "),
    ("سفر کردن", "سفر می‌کنم (present)", "To travel", "safar kardan", "safar mikonam  "),
    ("سفر کردن", "سفر کردم (past)", "To travel", "safar kardan", "safar kardam  "),
    ("خواندن", "می‌خوانم (present)", "To read", "khondan", "mikhonam  "),
    ("خواندن", "خواندم (past)", "To read", "khondan", "khondam  "),
    ("گرفتن", "می‌گیرم (present)", "To take", "gereftan", "migiram  "),
    ("گرفتن", "گرفتم (past)", "To take", "gereftan", "gereftam  "),
    ("دادن", "می‌دهم (present)", "To give", "dadan", "midaham  "),
    ("دادن", "دادم (past)", "To give", "dadan", "dadam  "),
    ("بازی کردن", "بازی می‌کنم (present)", "To play", "bazi kardan", "bazi mikonam  "),
    ("بازی کردن", "بازی کردم (past)", "To play", "bazi kardan", "bazi kardam  "),
    ("شستن", "می‌شوم (present)", "To wash", "shostan", "mishavam  "),
    ("شستن", "شستم (past)", "To wash", "shostan", "shostam  "),
    ("گشتن", "می‌گردم (present)", "To search", "gashtan", "migardam  "),
    ("گشتن", "گشتم (past)", "To search", "gashtan", "gashtam  "),
    ("گریختن", "می‌گریخم (present)", "To escape", "girikhtan", "migirikham  "),
    ("گریختن", "گریختم (past)", "To escape", "girikhtan", "girikhtam  "),
    ("خوراک دادن", "خوراک می‌دهم (present)", "To feed", "khorak dadan", "khorak midaham  "),
    ("خوراک دادن", "خوراک دادم (past)", "To feed", "khorak dadan", "khorak dadam  "),
    ("تداوم کردن", "تداوم می‌کنم (present)", "To persist", "tedavom kardan", "tedavom mikonam  "),
    ("تداوم کردن", "تداوم کردم (past)", "To persist", "tedavom kardan", "tedavom kardam  "),
    ("تحصیل کردن", "تحصیل می‌کنم (present)", "To study", "tahsil kardan", "tahsil mikonam  "),
    ("تحصیل کردن", "تحصیل کردم (past)", "To study", "tahsil kardan", "tahsil kardam  "),
    ("تسخیر کردن", "تسخیر می‌کنم (present)", "To conquer", "tasakhir kardan", "tasakhir mikonam  "),
    ("تسخیر کردن", "تسخیر کردم (past)", "To conquer", "tasakhir kardan", "tasakhir kardam  "),
    ("توصیه کردن", "توصیه می‌کنم (present)", "To recommend", "tavsiye kardan", "tavsiye mikonam  "),
    ("توصیه کردن", "توصیه کردم (past)", "To recommend", "tavsiye kardan", "tavsiye kardam  "),
    ("توقف کردن", "توقف می‌کنم (present)", "To halt", "toqof kardan", "toqof mikonam  "),
    ("توقف کردن", "توقف کردم (past)", "To halt", "toqof kardan", "toqof kardam  "),
    ("خریداری کردن", "خریداری می‌کنم (present)", "To purchase", "kharidari kardan", "kharidari mikonam  "),
    ("خریداری کردن", "خریداری کردم (past)", "To purchase", "kharidari kardan", "kharidari kardam  "),
    ("خودشناسی کردن", "خودشناسی می‌کنم (present)", "To introspect", "khodshenasi kardan", "khodshenasi mikonam  "),
    ("خودشناسی کردن", "خودشناسی کردم (past)", "To introspect", "khodshenasi kardan", "khodshenasi kardam  "),
    ("زیرساخت دادن", "زیرساخت می‌دهم (present)", "To provide infrastructure", "zirsakhthadan", "zirsakhth mideham  "),
    ("زیرساخت دادن", "زیرساخت دادم (past)", "To provide infrastructure", "zirsakhthadan", "zirsakhth dadam  "),
    ("ساختن", "می‌سازم (present)", "To create", "sakhtan", "misazam  "),
    ("ساختن", "ساختم (past)", "To create", "sakhtan", "sakhtam  "),
    ("سرپرستی کردن", "سرپرستی می‌کنم (present)", "To supervise", "sarpasti kardan", "sarpasti mikonam  "),
    ("سرپرستی کردن", "سرپرستی کردم (past)", "To supervise", "sarpasti kardan", "sarpasti kardam  "),
    ("شناسایی کردن", "شناسایی می‌کنم (present)", "To identify", "shenasa'i kardan", "shenasa'i mikonam  "),
    ("شناسایی کردن", "شناسایی کردم (past)", "To identify", "shenasa'i kardan", "shenasa'i kardam  "),
    ("شکست دادن", "شکست می‌دهم (present)", "To defeat", "shekast dadan", "shekast midaham  "),
    ("شکست دادن", "شکست دادم (past)", "To defeat", "shekast dadan", "shekast dadam  "),
    ("شمارش کردن", "شمارش می‌کنم (present)", "To count", "shomarash kardan", "shomarash mikonam  "),
    ("شمارش کردن", "شمارش کردم (past)", "To count", "shomarash kardan", "shomarash kardam  "),
    ("شکایت کردن", "شکایت می‌کنم (present)", "To complain", "shekayat kardan", "shekayat mikonam  "),
    ("شکایت کردن", "شکایت کردم (past)", "To complain", "shekayat kardan", "shekayat kardam  "),
    ("فرار کردن", "فرار می‌کنم (present)", "To escape", "farar kardan", "farar mikonam  "),
    ("فرار کردن", "فرار کردم (past)", "To escape", "farar kardan", "farar kardam  "),
    ("فهمیدن", "می‌فهمم (present)", "To understand", "fahmidan", "mifahmam  "),
    ("فهمیدن", "فهمیدم (past)", "To understand", "fahmidan", "fahmidam  "),
    ("کاوش کردن", "کاوش می‌کنم (present)", "To explore", "kavosh kardan", "kavosh mikonam  "),
    ("کاوش کردن", "کاوش کردم (past)", "To explore", "kavosh kardan", "kavosh kardam  "),
    ("گل کاری کردن", "گل کاری می‌کنم (present)", "To manipulate", "golkari kardan", "golkari mikonam  "),
    ("گل کاری کردن", "گل کاری کردم (past)", "To manipulate", "golkari kardan", "golkari kardam  "),
    ("گم کردن", "گم می‌شوم (present)", "To get lost", "gom kardan", "gom mishavam  "),
    ("گم کردن", "گم شدم (past)", "To get lost", "gom kardan", "gom shodam  "),
    ("گم کردن", "گم می‌کنم (present)", "To lose", "gom kardan", "gom mikonam  "),
    ("گم کردن", "گم کردم (past)", "To lose", "gom kardan", "gom kardam  "),
    ("لغو کردن", "لغو می‌کنم (present)", "To cancel", "laghv kardan", "laghv mikonam  "),
    ("لغو کردن", "لغو کردم (past)", "To cancel", "laghv kardan", "laghv kardam  "),
    ("محافظت کردن", "محافظت می‌کنم (present)", "To protect", "mahafazat kardan", "mahafazat mikonam  "),
    ("محافظت کردن", "محافظت کردم (past)", "To protect", "mahafazat kardan", "mahafazat kardam  "),
    ("هدایت کردن", "هدایت می‌کنم (present)", "To guide", "hedayat kardan", "hedayat mikonam  "),
    ("هدایت کردن", "هدایت کردم (past)", "To guide", "hedayat kardan", "hedayat kardam  "),
    ("بازی کردن", "بازی می‌کنم (present)", "To play", "bazi kardan", "bazi mikonam  "),
    ("بازی کردن", "بازی کردم (past)", "To play", "bazi kardan", "bazi kardam  "),
    ("پیاده روی کردن", "پیاده روی می‌کنم (present)", "To walk", "piadeh ravi kardan", "piadeh ravi mikonam  "),
    ("پیاده روی کردن", "پیاده روی کردم (past)", "To walk", "piadeh ravi kardan", "piadeh ravi kardam  "),
    ("نواختن", "نواختم (past)", "To play (an instrument)", "navakhtan", "navakhtam  "),
    ("خواستن", "خواهم (future)", "To want", "khastan", "khaham (future)"),
    ("دیدن", "می‌بینم (present)", "To see", "didan", "mibinam  "),
    ("دیدن", "دیدم (past)", "To see", "didan", "didam  "),
    ("شرکت کردن", "شرکت می‌کنم (present)", "To participate", "sherkat kardan", "sherkat mikonam  "),
    ("شرکت کردن", "شرکت کردم (past)", "To participate", "sherkat kardan", "sherkat kardam  "),
    ("خیاطی کردن", "خیاطی می‌کنم (present)", "To sew", "khiyati kardan", "khiyati mikonam  "),
    ("خیاطی کردن", "خیاطی کردم (past)", "To sew", "khiyati kardan", "khiyati kardam  "),
    ("رانندگی کردن", "رانندگی می‌کنم (present)", "To drive", "ranandegi kardan", "ranandegi mikonam  "),
    ("رانندگی کردن", "رانندگی کردم (past)", "To drive", "ranandegi kardan", "ranandegi kardam  "),
    ("رقصیدن", "رقص می‌کنم (present)", "To dance", "raqsidan", "raqs mikonam  "),
    ("رقصیدن", "رقصیدم (past)", "To dance", "raqsidan", "raqsidam  "),
    ("مطالعه کردن", "مطالعه می‌کنم (present)", "To study", "motale'eh kardan", "motale'eh mikonam  "),
    ("مطالعه کردن", "مطالعه کردم (past)", "To study", "motale'eh kardan", "motale'eh kardam  "),
    ("فراموش کردن", "فراموش می‌کنم (present)", "To forget", "foro'mosh kardan", "foro'mosh mikonam  "),
    ("فراموش کردن", "فراموش کردم (past)", "To forget", "foro'mosh kardan", "foro'mosh kardam  "),
    ("گم کردن", "گم می‌شوم (present)", "To get lost", "gom kardan", "gom mishavam  "),
    ("گم کردن", "گم شدم (past)", "To get lost", "gom kardan", "gom shodam  "),
    ("خندیدن", "خندمی (future)", "To laugh", "khandidan", "khahami (future)"),
    ("درخت کاری کردن", "درخت کاری می‌کنم (present)", "To carve", "darkh kari kardan", "darkh kari mikonam  "),
    ("درخت کاری کردن", "درخت کاری کردم (past)", "To carve", "darkh kari kardan", "darkh kari kardam  "),
    ("نجات دادن", "نجات می‌دهم (present)", "To save", "nejat dadan", "nejat midaham  "),
    ("نجات دادن", "نجات دادم (past)", "To save", "nejat dadan", "nejat dadam  "),
    ("مهاجرت کردن", "مهاجرت می‌کنم (present)", "To migrate", "mohajerat kardan", "mohajerat mikonam  "),
    ("مهاجرت کردن", "مهاجرت کردم (past)", "To migrate", "mohajerat kardan", "mohajerat kardam  "),
    ("دزدی کردن", "دزدی می‌کنم (present)", "To steal", "dozdi kardan", "dozdi mikonam  "),
    ("دزدی کردن", "دزدی کردم (past)", "To steal", "dozdi kardan", "dozdi kardam  "),
    ("آرام کردن", "آرام می‌کنم (present)", "To calm", "aram kardan", "aram mikonam  "),
    ("آرام کردن", "آرام کردم (past)", "To calm", "aram kardan", "aram kardam  "),
    ("سفر کردن", "سفر می‌کنم (present)", "To travel", "safar kardan", "safar mikonam  "),
    ("سفر کردن", "سفر کردم (past)", "To travel", "safar kardan", "safar kardam  "),
    ("خوراک دادن", "خوراک می‌دهم (present)", "To feed", "khorak dadan", "khorak midaham  "),
    ("خوراک دادن", "خوراک دادم (past)", "To feed", "khorak dadan", "khorak dadam  "),
    ("گریختن", "گریختم (past)", "To escape", "girikhtan", "girikhtam  "),
    ("فهمیدن", "می‌فهمم (present)", "To understand", "fahmidan", "mifahmam  "),
    ("فهمیدن", "فهمیدم (past)", "To understand", "fahmidan", "fahmidam  "),
    ("کاوش کردن", "کاوش می‌کنم (present)", "To explore", "kavosh kardan", "kavosh mikonam  "),
    ("کاوش کردن", "کاوش کردم (past)", "To explore", "kavosh kardan", "kavosh kardam  "),
    ("گل کاری کردن", "گل کاری می‌کنم (present)", "To manipulate", "golkari kardan", "golkari mikonam  "),
    ("گل کاری کردن", "گل کاری کردم (past)", "To manipulate", "golkari kardan", "golkari kardam  "),
    ("گم کردن", "گم می‌کنم (present)", "To lose", "gom kardan", "gom mikonam  "),
    ("گم کردن", "گم کردم (past)", "To lose", "gom kardan", "gom kardam  "),
    ("لغو کردن", "لغو می‌کنم (present)", "To cancel", "laghv kardan", "laghv mikonam  "),
    ("لغو کردن", "لغو کردم (past)", "To cancel", "laghv kardan", "laghv kardam  "),
    ("محافظت کردن", "محافظت می‌کنم (present)", "To protect", "mahafazat kardan", "mahafazat mikonam  "),
    ("محافظت کردن", "محافظت کردم (past)", "To protect", "mahafazat kardan", "mahafazat kardam  "),
    ("هدایت کردن", "هدایت می‌کنم (present)", "To guide", "hedayat kardan", "hedayat mikonam  "),
    ("هدایت کردن", "هدایت کردم (past)", "To guide", "hedayat kardan", "hedayat kardam  "),
    ("شکست دادن", "شکست می‌دهم (present)", "To break", "shekast dadan", "shekast midaham (present)"),
    ("شکست دادن", "شکست دادم (past)", "To break", "shekast dadan", "shekast dadam (past)"),
    ("نجات دادن", "نجات می‌دهم (present)", "To rescue", "nejat dadan", "nejat midaham (present)"),
    ("نجات دادن", "نجات دادم (past)", "To rescue", "nejat dadan", "nejat dadam (past)"),
    ("سر کردن", "سر می‌کنم (present)", "To turn", "sar kardan", "sar mikonam (present)"),
    ("سر کردن", "سر کردم (past)", "To turn", "sar kardan", "sar kardam (past)"),
    ("پرسیدن", "پرس می‌کنم (present)", "To ask", "porsidan", "pors mikonam (present)"),
    ("پرسیدن", "پرسیدم (past)", "To ask", "porsidan", "porsidam (past)"),
    ("خواندن", "می‌خوانم (present)", "To read", "khandidan", "mikhanam (present)"),
    ("خواندن", "خواندم (past)", "To read", "khandidan", "khandam (past)"),
    ("نوشیدن", "می‌نوشم (present)", "To drink", "noshidan", "minosham (present)"),
    ("نوشیدن", "نوشیدم (past)", "To drink", "noshidan", "noshidam (past)"),
    ("بیخیال شدن", "بیخیال می‌شوم (present)", "To become indifferent", "bikhial shodan", "bikhial mishavam (present)"),
    ("بیخیال شدن", "بیخیال شدم (past)", "To become indifferent", "bikhial shodan", "bikhial shodam (past)"),
    ("گفتن", "می‌گویم (present)", "To say", "goftan", "migooyam (present)"),
    ("گفتن", "گفتم (past)", "To say", "goftan", "goftam (past)"),
    ("ترسیدن", "می‌ترسم (present)", "To be afraid", "tarasidan", "mitarsam (present)"),
    ("ترسیدن", "ترسیدم (past)", "To be afraid", "tarasidan", "tarasidam (past)"),
    ("شنیدن", "می‌شنوم (present)", "To hear", "shenidan", "mishenavam (present)"),
    ("شنیدن", "شنیدم (past)", "To hear", "shenidan", "shenidam (past)"),
    ("گیر انداختن", "گیر می‌اندازم (present)", "To catch", "gir andakhtan", "gir miandazam (present)"),
    ("گیر انداختن", "گیر انداختم (past)", "To catch", "gir andakhtan", "gir andakhtam (past)"),
    ("خوراک دادن", "خوراک می‌دهم (present)", "To feed", "khorak dadan", "khorak midaham (present)"),
    ("خوراک دادن", "خوراک دادم (past)", "To feed", "khorak dadan", "khorak dadam (past)"),
    ("فرار کردن", "فرار می‌کنم (present)", "To flee", "farar kardan", "farar mikonam (present)"),
    ("فرار کردن", "فرار کردم (past)", "To flee", "farar kardan", "farar kardam (past)"),
    ("سر زدن", "سر می‌زنم (present)", "To hit", "sar zadan", "sar mizanam (present)"),
    ("سر زدن", "سر زدم (past)", "To hit", "sar zadan", "sar zadam (past)"),
    ("بلند کردن", "بلند می‌کنم (present)", "To lift", "boland kardan", "boland mikonam (present)"),
    ("بلند کردن", "بلند کردم (past)", "To lift", "boland kardan", "boland kardam (past)"),
    ("ترک کردن", "ترک می‌کنم (present)", "To abandon", "tark kardan", "tark mikonam (present)"),
    ("ترک کردن", "ترک کردم (past)", "To abandon", "tark kardan", "tark kardam (past)"),
    ("ترجیح دادن", "ترجیح می‌دهم (present)", "To prefer", "tarjih dadan", "tarjih midaham (present)"),
    ("ترجیح دادن", "ترجیح دادم (past)", "To prefer", "tarjih dadan", "tarjih dadam (past)"),
    ("پرتاب کردن", "پرتاب می‌کنم (present)", "To throw", "partab kardan", "partab mikonam (present)"),
    ("پرتاب کردن", "پرتاب کردم (past)", "To throw", "partab kardan", "partab kardam (past)"),
    ("نواختن", "می‌نوازم (present)", "To play (an instrument)", "navakhtan", "minavazam (present)"),
    ("نواختن", "نواختم (past)", "To play (an instrument)", "navakhtan", "navakhtam (past)"),
    ("تاب آوردن", "تاب آورم (future)", "To endure", "tabavardan", "tabavaram (future)"),
    ("تاب آوردن", "تاب آوردم (past)", "To endure", "tabavardan", "tabavardam (past)"),
    ("ترسیدن", "می‌ترسم (present)", "To dread", "tarasidan", "mitarsam (present)"),
    ("ترسیدن", "ترسیدم (past)", "To dread", "tarasidan", "tarasidam (past)"),
    ("پریدن", "می‌پرم (present)", "To jump", "paridan", "miparam (present)"),
    ("پریدن", "پریدم (past)", "To jump", "paridan", "paridam (past)"),
    ("رقابت کردن", "رقابت می‌کنم (present)", "To compete", "raqabat kardan", "raqabat mikonam (present)"),
    ("رقابت کردن", "رقابت کردم (past)", "To compete", "raqabat kardan", "raqabat kardam (past)"),
    ("شکار کردن", "شکار می‌کنم (present)", "To hunt", "shikar kardan", "shikar mikonam (present)"),
    ("شکار کردن", "شکار کردم (past)", "To hunt", "shikar kardan", "shikar kardam (past)"),
    ("متحد کردن", "متحد می‌کنم (present)", "To unite", "motahed kardan", "motahed mikonam (present)"),
    ("متحد کردن", "متحد کردم (past)", "To unite", "motahed kardan", "motahed kardam (past)"),
    ("شکایت کردن", "شکایت می‌کنم (present)", "To complain", "shikayat kardan", "shikayat mikonam (present)"),
    ("شکایت کردن", "شکایت کردم (past)", "To complain", "shikayat kardan", "shikayat kardam (past)"),
    ("حل کردن", "حل می‌کنم (present)", "To solve", "hal kardan", "hal mikonam (present)"),
    ("حل کردن", "حل کردم (past)", "To solve", "hal kardan", "hal kardam (past)"),
    ("معذرت خواهی کردن", "معذرت خواهی می‌کنم (present)", "To apologize", "ma'zerat khahi kardan", "ma'zerat khahi mikonam (present)"),
    ("معذرت خواهی کردن", "معذرت خواهی کردم (past)", "To apologize", "ma'zerat khahi kardan", "ma'zerat khahi kardam (past)"),
    ("عکس العمل نشان دادن", "عکس العمل نشان می‌دهم (present)", "To react", "aks alamal neshan dadan", "aks alamal neshan midaham (present)"),
    ("عکس العمل نشان دادن", "عکس العمل نشان دادم (past)", "To react", "aks alamal neshan dadan", "aks alamal neshan dadam (past)"),
    ("نظارت کردن", "نظارت می‌کنم (present)", "To supervise", "nazariat kardan", "nazariat mikonam (present)"),
    ("نظارت کردن", "نظارت کردم (past)", "To supervise", "nazariat kardan", "nazariat kardam (past)"),
    ("تربیت کردن", "تربیت می‌کنم (present)", "To educate", "tarbiyat kardan", "tarbiyat mikonam (present)"),
    ("تربیت کردن", "تربیت کردم (past)", "To educate", "tarbiyat kardan", "tarbiyat kardam (past)"),
    ("ترتیب دادن", "ترتیب می‌دهم (present)", "To arrange", "tartib dadan", "tartib midaham (present)"),
    ("ترتیب دادن", "ترتیب دادم (past)", "To arrange", "tartib dadan", "tartib dadam (past)"),
    ("شروع کردن", "شروع می‌کنم (present)", "To begin", "shoroo kardan", "shoroo mikonam (present)"),
    ("شروع کردن", "شروع کردم (past)", "To begin", "shoroo kardan", "shoroo kardam (past)"),
    ("پخت کردن", "پخت می‌کنم (present)", "To cook", "pakht kardan", "pakht mikonam (present)"),
    ("پخت کردن", "پخت کردم (past)", "To cook", "pakht kardan", "pakht kardam (past)"),
    ("دست زدن", "دست می‌زنم (present)", "To applaud", "dast zadan", "dast mizanam (present)"),
    ("دست زدن", "دست زدم (past)", "To applaud", "dast zadan", "dast zadam (past)"),
    ("حاکم شدن", "حاکم می‌شوم (present)", "To rule", "hakam shodan", "hakam mishavam (present)"),
    ("حاکم شدن", "حاکم شدم (past)", "To rule", "hakam shodan", "hakam shodam (past)"),
    ("مخالفت کردن", "مخالفت می‌کنم (present)", "To object", "mokhalefat kardan", "mokhalefat mikonam (present)"),
    ("مخالفت کردن", "مخالفت کردم (past)", "To object", "mokhalefat kardan", "mokhalefat kardam (past)"),
    ("بازی کردن", "بازی می‌کنم (present)", "To play", "bazi kardan", "bazi mikonam (present)"),
    ("بازی کردن", "بازی کردم (past)", "To play", "bazi kardan", "bazi kardam (past)"),
    ("انتخاب کردن", "انتخاب می‌کنم (present)", "To choose", "entekhab kardan", "entekhab mikonam (present)"),
    ("انتخاب کردن", "انتخاب کردم (past)", "To choose", "entekhab kardan", "entekhab kardam (past)"),
    ("تشویق کردن", "تشویق می‌کنم (present)", "To encourage", "tashvigh kardan", "tashvigh mikonam (present)"),
    ("تشویق کردن", "تشویق کردم (past)", "To encourage", "tashvigh kardan", "tashvigh kardam (past)"),
    ("رانندگی کردن", "رانندگی می‌کنم (present)", "To drive", "ranandegi kardan", "ranandegi mikonam (present)"),
    ("رانندگی کردن", "رانندگی کردم (past)", "To drive", "ranandegi kardan", "ranandegi kardam (past)"),
    ("کاوش کردن", "کاوش می‌کنم (present)", "To explore", "kavosh kardan", "kavosh mikonam (present)"),
    ("کاوش کردن", "کاوش کردم (past)", "To explore", "kavosh kardan", "kavosh kardam (past)"),
    ("گل کاری کردن", "گل کاری می‌کنم (present)", "To manipulate", "golkari kardan", "golkari mikonam (present)"),
    ("گل کاری کردن", "گل کاری کردم (past)", "To manipulate", "golkari kardan", "golkari kardam (past)"),
    ("گم کردن", "گم می‌کنم (present)", "To lose", "gom kardan", "gom mikonam (present)"),
    ("گم کردن", "گم کردم (past)", "To lose", "gom kardan", "gom kardam (past)"),
    ("لغو کردن", "لغو می‌کنم (present)", "To cancel", "laghv kardan", "laghv mikonam (present)"),
    ("لغو کردن", "لغو کردم (past)", "To cancel", "laghv kardan", "laghv kardam (past)"),
    ("محافظت کردن", "محافظت می‌کنم (present)", "To protect", "mahafazat kardan", "mahafazat mikonam (present)"),
    ("محافظت کردن", "محافظت کردم (past)", "To protect", "mahafazat kardan", "mahafazat kardam (past)"),
    ("هدایت کردن", "هدایت می‌کنم (present)", "To guide", "hedayat kardan", "hedayat mikonam (present)"),
    ("هدایت کردن", "هدایت کردم (past)", "To guide", "hedayat kardan", "hedayat kardam (past)"),
    ("بلند کردن", "بلند می‌کنم (present)", "To lift", "boland kardan", "boland mikonam (present)"),
    ("بلند کردن", "بلند کردم (past)", "To lift", "boland kardan", "boland kardam (past)"),
    ("ترک کردن", "ترک می‌کنم (present)", "To abandon", "tark kardan", "tark mikonam (present)"),
    ("ترک کردن", "ترک کردم (past)", "To abandon", "tark kardan", "tark kardam (past)"),
    ("ترجیح دادن", "ترجیح می‌دهم (present)", "To prefer", "tarjih dadan", "tarjih midaham (present)"),
    ("ترجیح دادن", "ترجیح دادم (past)", "To prefer", "tarjih dadan", "tarjih dadam (past)"),
    ("پرتاب کردن", "پرتاب می‌کنم (present)", "To throw", "partab kardan", "partab mikonam (present)"),
    ("پرتاب کردن", "پرتاب کردم (past)", "To throw", "partab kardan", "partab kardam (past)"),
    ("نواختن", "می‌نوازم (present)", "To play (an instrument)", "navakhtan", "minavazam (present)"),
    ("نواختن", "نواختم (past)", "To play (an instrument)", "navakhtan", "navakhtam (past)"),
    ("تاب آوردن", "تاب آورم (future)", "To endure", "tabavardan", "tabavaram (future)"),
    ("تاب آوردن", "تاب آوردم (past)", "To endure", "tabavardan", "tabavardam (past)"),
    ("ترسیدن", "می‌ترسم (present)", "To dread", "tarasidan", "mitarsam (present)"),
    ("ترسیدن", "ترسیدم (past)", "To dread", "tarasidan", "tarasidam (past)"),
    ("پریدن", "می‌پرم (present)", "To jump", "paridan", "miparam (present)"),
    ("پریدن", "پریدم (past)", "To jump", "paridan", "paridam (past)"),
    ("رقابت کردن", "رقابت می‌کنم (present)", "To compete", "raqabat kardan", "raqabat mikonam (present)"),
    ("رقابت کردن", "رقابت کردم (past)", "To compete", "raqabat kardan", "raqabat kardam (past)"),
    ("شکار کردن", "شکار می‌کنم (present)", "To hunt", "shikar kardan", "shikar mikonam (present)"),
    ("شکار کردن", "شکار کردم (past)", "To hunt", "shikar kardan", "shikar kardam (past)"),
    ("متحد کردن", "متحد می‌کنم (present)", "To unite", "motahed kardan", "motahed mikonam (present)"),
    ("متحد کردن", "متحد کردم (past)", "To unite", "motahed kardan", "motahed kardam (past)"),
    ("شکایت کردن", "شکایت می‌کنم (present)", "To complain", "shikayat kardan", "shikayat mikonam (present)"),
    ("شکایت کردن", "شکایت کردم (past)", "To complain", "shikayat kardan", "shikayat kardam (past)"),
    ("حل کردن", "حل می‌کنم (present)", "To solve", "hal kardan", "hal mikonam (present)"),
    ("حل کردن", "حل کردم (past)", "To solve", "hal kardan", "hal kardam (past)"),
    ("معذرت خواهی کردن", "معذرت خواهی می‌کنم (present)", "To apologize", "ma'zerat khahi kardan", "ma'zerat khahi mikonam (present)"),
    ("معذرت خواهی کردن", "معذرت خواهی کردم (past)", "To apologize", "ma'zerat khahi kardan", "ma'zerat khahi kardam (past)"),
    ("عکس العمل نشان دادن", "عکس العمل نشان می‌دهم (present)", "To react", "aks alamal neshan dadan", "aks alamal neshan midaham (present)"),
    ("عکس العمل نشان دادن", "عکس العمل نشان دادم (past)", "To react", "aks alamal neshan dadan", "aks alamal neshan dadam (past)"),
    ("نظارت کردن", "نظارت می‌کنم (present)", "To supervise", "nazariat kardan", "nazariat mikonam (present)"),
    ("نظارت کردن", "نظارت کردم (past)", "To supervise", "nazariat kardan", "nazariat kardam (past)"),
    ("تربیت کردن", "تربیت می‌کنم (present)", "To educate", "tarbiyat kardan", "tarbiyat mikonam (present)"),
    ("تربیت کردن", "تربیت کردم (past)", "To educate", "tarbiyat kardan", "tarbiyat kardam (past)"),
    ("ترتیب دادن", "ترتیب می‌دهم (present)", "To arrange", "tartib dadan", "tartib midaham (present)"),
    ("ترتیب دادن", "ترتیب دادم (past)", "To arrange", "tartib dadan", "tartib dadam (past)"),
    ("شروع کردن", "شروع می‌کنم (present)", "To begin", "shoroo kardan", "shoroo mikonam (present)"),
    ("شروع کردن", "شروع کردم (past)", "To begin", "shoroo kardan", "shoroo kardam (past)"),
    ("پخت کردن", "پخت می‌کنم (present)", "To cook", "pakht kardan", "pakht mikonam (present)"),
    ("پخت کردن", "پخت کردم (past)", "To cook", "pakht kardan", "pakht kardam (past)"),
    ("دست زدن", "دست می‌زنم (present)", "To applaud", "dast zadan", "dast mizanam (present)"),
    ("دست زدن", "دست زدم (past)", "To applaud", "dast zadan", "dast zadam (past)"),
    ("حاکم شدن", "حاکم می‌شوم (present)", "To rule", "hakam shodan", "hakam mishavam (present)"),
    ("حاکم شدن", "حاکم شدم (past)", "To rule", "hakam shodan", "hakam shodam (past)"),
    ("مخالفت کردن", "مخالفت می‌کنم (present)", "To object", "mokhalefat kardan", "mokhalefat mikonam (present)"),
    ("مخالفت کردن", "مخالفت کردم (past)", "To object", "mokhalefat kardan", "mokhalefat kardam (past)"),
    ("بازی کردن", "بازی می‌کنم (present)", "To play", "bazi kardan", "bazi mikonam (present)"),
    ("بازی کردن", "بازی کردم (past)", "To play", "bazi kardan", "bazi kardam (past)"),
    ("انتخاب کردن", "انتخاب می‌کنم (present)", "To choose", "entekhab kardan", "entekhab mikonam (present)"),
    ("انتخاب کردن", "انتخاب کردم (past)", "To choose", "entekhab kardan", "entekhab kardam (past)"),
    ("تشویق کردن", "تشویق می‌کنم (present)", "To encourage", "tashvigh kardan", "tashvigh mikonam (present)"),
    ("تشویق کردن", "تشویق کردم (past)", "To encourage", "tashvigh kardan", "tashvigh kardam (past)"),
    ("رانندگی کردن", "رانندگی می‌کنم (present)", "To drive", "ranandegi kardan", "ranandegi mikonam (present)"),
    ("رانندگی کردن", "رانندگی کردم (past)", "To drive", "ranandegi kardan", "ranandegi kardam (past)"),
    ("کاوش کردن", "کاوش می‌کنم (present)", "To explore", "kavosh kardan", "kavosh mikonam (present)"),
    ("کاوش کردن", "کاوش کردم (past)", "To explore", "kavosh kardan", "kavosh kardam (past)"),
    ("گل کاری کردن", "گل کاری می‌کنم (present)", "To manipulate", "golkari kardan", "golkari mikonam (present)"),
    ("گل کاری کردن", "گل کاری کردم (past)", "To manipulate", "golkari kardan", "golkari kardam (past)"),
    ("گم کردن", "گم می‌کنم (present)", "To lose", "gom kardan", "gom mikonam (present)"),
    ("گم کردن", "گم کردم (past)", "To lose", "gom kardan", "gom kardam (past)"),
    ("لغو کردن", "لغو می‌کنم (present)", "To cancel", "laghv kardan", "laghv mikonam (present)"),
    ("لغو کردن", "لغو کردم (past)", "To cancel", "laghv kardan", "laghv kardam (past)"),
    ("محافظت کردن", "محافظت می‌کنم (present)", "To protect", "mahafazat kardan", "mahafazat mikonam (present)"),
    ("محافظت کردن", "محافظت کردم (past)", "To protect", "mahafazat kardan", "mahafazat kardam (past)"),
    ("هدایت کردن", "هدایت می‌کنم (present)", "To guide", "hedayat kardan", "hedayat mikonam (present)"),
    ("هدایت کردن", "هدایت کردم (past)", "To guide", "hedayat kardan", "hedayat kardam (past)"),
    ("پوشیدن", "می‌پوشم (present)", "To wear", "pusheedan", "miposham (present)"),
    ("پوشیدن", "پوشیدم (past)", "To wear", "pusheedan", "pusheedam (past)"),
    ("ترتیب دادن", "ترتیب می‌دهم (present)", "To arrange", "tartib dadan", "tartib midaham (present)"),
    ("ترتیب دادن", "ترتیب دادم (past)", "To arrange", "tartib dadan", "tartib dadam (past)"),
    ("بپرسیدن", "می‌پرسم (present)", "To ask", "be-porsidan", "miporsam (present)"),
    ("بپرسیدن", "پرسیدم (past)", "To ask", "be-porsidan", "porsidam (past)"),
    ("معامله کردن", "معامله می‌کنم (present)", "To bargain", "ma'amaleh kardan", "ma'amaleh mikonam (present)"),
    ("معامله کردن", "معامله کردم (past)", "To bargain", "ma'amaleh kardan", "ma'amaleh kardam (past)"),
    ("دعوت کردن", "دعوت می‌کنم (present)", "To invite", "davat kardan", "davat mikonam (present)"),
    ("دعوت کردن", "دعوت کردم (past)", "To invite", "davat kardan", "davat kardam (past)"),
    ("بایستن", "می‌بایم (present)", "To need", "baayestan", "mibaayam (present)"),
    ("بایستن", "بایستم (past)", "To need", "baayestan", "baayestam (past)"),
    ("مشغول کردن", "مشغول می‌کنم (present)", "To occupy", "mashghool kardan", "mashghool mikonam (present)"),
    ("مشغول کردن", "مشغول کردم (past)", "To occupy", "mashghool kardan", "mashghool kardam (past)"),
    ("واکنش نشان دادن", "واکنش نشان می‌دهم (present)", "To react", "vakansh neshan dadan", "vakansh neshan midaham (present)"),
    ("واکنش نشان دادن", "واکنش نشان دادم (past)", "To react", "vakansh neshan dadan", "vakansh neshan dadam (past)"),
    ("ترجیح دادن", "ترجیح می‌دهم (present)", "To prefer", "tarjih dadan", "tarjih midaham (present)"),
    ("ترجیح دادن", "ترجیح دادم (past)", "To prefer", "tarjih dadan", "tarjih dadam (past)"),
    ("اعتماد کردن", "اعتماد می‌کنم (present)", "To trust", "etemad kardan", "etemad mikonam (present)"),
    ("اعتماد کردن", "اعتماد کردم (past)", "To trust", "etemad kardan", "etemad kardam (past)"),
    ("بررسی کردن", "بررسی می‌کنم (present)", "To investigate", "barrasi kardan", "barrasi mikonam (present)"),
    ("بررسی کردن", "بررسی کردم (past)", "To investigate", "barrasi kardan", "barrasi kardam (past)"),
    ("حمله کردن", "حمله می‌کنم (present)", "To attack", "hamele kardan", "hamele mikonam (present)"),
    ("حمله کردن", "حمله کردم (past)", "To attack", "hamele kardan", "hamele kardam (past)"),
    ("پشتیبانی کردن", "پشتیبانی می‌کنم (present)", "To support", "pashtibani kardan", "pashtibani mikonam (present)"),
    ("پشتیبانی کردن", "پشتیبانی کردم (past)", "To support", "pashtibani kardan", "pashtibani kardam (past)"),
    ("معلمی کردن", "معلمی می‌کنم (present)", "To teach", "moallemi kardan", "moallemi mikonam (present)"),
    ("معلمی کردن", "معلمی کردم (past)", "To teach", "moallemi kardan", "moallemi kardam (past)"),
    ("مذاکره کردن", "مذاکره می‌کنم (present)", "To negotiate", "mazakhare kardan", "mazakhare mikonam (present)"),
    ("مذاکره کردن", "مذاکره کردم (past)", "To negotiate", "mazakhare kardan", "mazakhare kardam (past)"),
    ("تحصیل کردن", "تحصیل می‌کنم (present)", "To study", "tahsil kardan", "tahsil mikonam (present)"),
    ("تحصیل کردن", "تحصیل کردم (past)", "To study", "tahsil kardan", "tahsil kardam (past)"),
    ("رانندگی کردن", "رانندگی می‌کنم (present)", "To drive", "ranandegi kardan", "ranandegi mikonam (present)"),
    ("رانندگی کردن", "رانندگی کردم (past)", "To drive", "ranandegi kardan", "ranandegi kardam (past)"),
    ("بگردانیدن", "می‌گردانم (present)", "To turn", "be-gardanidan", "migardanam (present)"),
    ("بگردانیدن", "گردانیدم (past)", "To turn", "be-gardanidan", "gardanidam (past)"),
    ("آزمایش کردن", "آزمایش می‌کنم (present)", "To test", "azmaayesh kardan", "azmaayesh mikonam (present)"),
    ("آزمایش کردن", "آزمایش کردم (past)", "To test", "azmaayesh kardan", "azmaayesh kardam (past)"),
    ("دور زدن", "دور می‌زنم (present)", "To hit", "dor zadan", "dor mizanam (present)"),
    ("دور زدن", "دور زدم (past)", "To hit", "dor zadan", "dor zadam (past)"),
    ("پرواز کردن", "پرواز می‌کنم (present)", "To fly", "parvaz kardan", "parvaz mikonam (present)"),
    ("پرواز کردن", "پرواز کردم (past)", "To fly", "parvaz kardan", "parvaz kardam (past)"),
    ("حذف کردن", "حذف می‌کنم (present)", "To delete", "hazf kardan", "hazf mikonam (present)"),
    ("حذف کردن", "حذف کردم (past)", "To delete", "hazf kardan", "hazf kardam (past)"),
    ("زندگی کردن", "زندگی می‌کنم (present)", "To live", "zendegi kardan", "zendegi mikonam (present)"),
    ("زندگی کردن", "زندگی کردم (past)", "To live", "zendegi kardan", "zendegi kardam (past)"),
    ("نمایش دادن", "نمایش می‌دهم (present)", "To display", "namaayesh dadan", "namaayesh midaham (present)"),
    ("نمایش دادن", "نمایش دادم (past)", "To display", "namaayesh dadan", "namaayesh dadam (past)"),
    ("رساندن", "رساندم (future)", "To convey", "rasandan", "rasandam (future)"),
    ("رساندن", "رساندم (past)", "To convey", "rasandan", "rasandam (past)"),
    ("جدا کردن", "جدا می‌کنم (present)", "To separate", "joda kardan", "joda mikonam (present)"),
    ("جدا کردن", "جدا کردم (past)", "To separate", "joda kardan", "joda kardam (past)"),
    ("پاک کردن", "پاک می‌کنم (present)", "To clean", "paak kardan", "paak mikonam (present)"),
    ("پاک کردن", "پاک کردم (past)", "To clean", "paak kardan", "paak kardam (past)"),
    ("مجروح کردن", "مجروح می‌کنم (present)", "To wound", "majrooh kardan", "majrooh mikonam (present)"),
    ("مجروح کردن", "مجروح کردم (past)", "To wound", "majrooh kardan", "majrooh kardam (past)"),
    ("راه انداختن", "راه انداختم (future)", "To launch", "raah andaakhtan", "raah andaakhtam (future)"),
    ("راه انداختن", "راه انداختم (past)", "To launch", "raah andaakhtan", "raah andaakhtam (past)"),
    ("سوزاندن", "می‌سوزم (present)", "To burn", "soozandan", "misoozam (present)"),
    ("سوزاندن", "سوزیدم (past)", "To burn", "soozandan", "soozidam (past)"),
    ("پیشنهاد دادن", "پیشنهاد می‌دهم (present)", "To suggest", "pishnehad dadan", "pishnehad mikonam (present)"),
    ("پیشنهاد دادن", "پیشنهاد دادم (past)", "To suggest", "pishnehad dadan", "pishnehad dadam (past)"),
    ("متهم کردن", "متهم می‌کنم (present)", "To accuse", "moteham kardan", "moteham mikonam (present)"),
    ("متهم کردن", "متهم کردم (past)", "To accuse", "moteham kardan", "moteham kardam (past)"),
    ("ترک کردن", "ترک می‌کنم (present)", "To abandon", "tarak kardan", "tarak mikonam (present)"),
    ("ترک کردن", "ترک کردم (past)", "To abandon", "tarak kardan", "tarak kardam (past)"),
    ("بیخیال شدن", "بیخیال می‌شوم (present)", "To become indifferent", "bikhaal shodan", "bikhaal mishavam (present)"),
    ("بیخیال شدن", "بیخیال شدم (past)", "To become indifferent", "bikhaal shodan", "bikhaal shodam (past)"),
    ("شکست دادن", "شکست می‌دهم (present)", "To break", "shekast dadan", "shekast mikonam (present)"),
    ("شکست دادن", "شکست دادم (past)", "To break", "shekast dadan", "shekast dadam (past)"),
    ("مهاجمه کردن", "مهاجمه می‌کنم (present)", "To invade", "mohajameh kardan", "mohajameh mikonam (present)"),
    ("مهاجمه کردن", "مهاجمه کردم (past)", "To invade", "mohajameh kardan", "mohajameh kardam (past)"),
    ("آزار دادن", "آزار می‌دهم (present)", "To harass", "azaar dadan", "azaar midaham (present)"),
    ("آزار دادن", "آزار دادم (past)", "To harass", "azaar dadan", "azaar dadam (past)"),
    ("سفر کردن", "سفر می‌کنم (present)", "To journey", "safar kardan", "safar mikonam (present)"),
    ("سفر کردن", "سفر کردم (past)", "To journey", "safar kardan", "safar kardam (past)"),
    ("پیشنهاد کردن", "پیشنهاد می‌کنم (present)", "To propose", "pishnehad kardan", "pishnehad mikonam (present)"),
    ("پیشنهاد کردن", "پیشنهاد کردم (past)", "To propose", "pishnehad kardan", "pishnehad kardam (past)"),
    ("باور کردن", "باور می‌کنم (present)", "To believe", "baavar kardan", "baavar mikonam (present)"),
    ("باور کردن", "باور کردم (past)", "To believe", "baavar kardan", "baavar kardam (past)"),
    ("تخریب کردن", "تخریب می‌کنم (present)", "To destroy", "takhrib kardan", "takhrib mikonam (present)"),
    ("تخریب کردن", "تخریب کردم (past)", "To destroy", "takhrib kardan", "takhrib kardam (past)"),
    ("شکست دادن", "می‌شکنم (present)", "To shatter", "shekast dadan", "mishkanam (present)"),
    ("شکست دادن", "شکست دادم (past)", "To shatter", "shekast dadan", "shekast dadam (past)"),
    ("مهاجمه کردن", "مهاجمه می‌کنم (present)", "To assault", "mohajameh kardan", "mohajameh mikonam (present)"),
    ("مهاجمه کردن", "مهاجمه کردم (past)", "To assault", "mohajameh kardan", "mohajameh kardam (past)"),
    ("آزار دادن", "آزار می‌دهم (present)", "To torment", "azaar dadan", "azaar midaham (present)"),
    ("آزار دادن", "آزار دادم (past)", "To torment", "azaar dadan", "azaar dadam (past)"),
    ("سفر کردن", "سفر می‌کنم (present)", "To voyage", "safar kardan", "safar mikonam (present)"),
    ("سفر کردن", "سفر کردم (past)", "To voyage", "safar kardan", "safar kardam (past)"),
    ("پیشنهاد کردن", "پیشنهاد می‌کنم (present)", "To proffer", "pishnehad kardan", "pishnehad mikonam (present)"),
    ("پیشنهاد کردن", "پیشنهاد کردم (past)", "To proffer", "pishnehad kardan", "pishnehad kardam (past)"),
    ("باور کردن", "باور می‌کنم (present)", "To credit", "baavar kardan", "baavar mikonam (present)"),
    ("باور کردن", "باور کردم (past)", "To credit", "baavar kardan", "baavar kardam (past)"),
    ("تخریب کردن", "تخریب می‌کنم (present)", "To wreck", "takhrib kardan", "takhrib mikonam (present)"),
    ("تخریب کردن", "تخریب کردم (past)", "To wreck", "takhrib kardan", "takhrib kardam (past)"),
    ("رقصیدن", "می‌رقصم (present)", "To waltz", "raqsidan", "miraghsam (present)"),
    ("رقصیدن", "رقصیدم (past)", "To waltz", "raqsidan", "raqsidam (past)"),
    ("عشقیدن", "می‌عشقم (present)", "To worship", "eshqidan", "miaeshqam (present)"),
    ("عشقیدن", "عشقیدم (past)", "To worship", "eshqidan", "eshqidam (past)"),
    ("مسافرت کردن", "می‌مسافرت کنم (present)", "To sightsee", "mosaferat kardan", "mimosaferat konam (present)"),
    ("مسافرت کردن", "مسافرت کردم (past)", "To sightsee", "mosaferat kardan", "mosaferat kardam (past)"),
    ("معاف کردن", "می‌معاف کنم (present)", "To remit", "ma'af kardan", "mima'af konam (present)"),
    ("معاف کردن", "معاف کردم (past)", "To remit", "ma'af kardan", "ma'af kardam (past)"),
    ("دست زدن", "می‌دست زنم (present)", "To clap", "dast zadan", "midast zanam (present)"),
    ("دست زدن", "دست زدم (past)", "To clap", "dast zadan", "dast zadam (past)"),
    ("ترسیدن", "می‌ترسم (present)", "To dread", "tarasidan", "mitarsam (present)"),
    ("ترسیدن", "ترسیدم (past)", "To dread", "tarasidan", "tarasidam (past)"),
    ("تغییر دادن", "می‌تغییر دهم (present)", "To alter", "taghir dadan", "mitaghdir deham (present)"),
    ("تغییر دادن", "تغییر دادم (past)", "To alter", "taghir dadan", "taghir dadam (past)"),
    ("مسابقه کردن", "می‌مسابقه کنم (present)", "To vie", "mosabeghe kardan", "mimasabeghe konam (present)"),
    ("مسابقه کردن", "مسابقه کردم (past)", "To vie", "mosabeghe kardan", "mosabeghe kardam (past)"),
    ("خواندن", "می‌خوانم (present)", "To read", "khondan", "mikhonam (present)"),
    ("خواندن", "خواندم (past)", "To read", "khondan", "khondam (past)"),
    ("نوشیدن", "می‌نوشم (present)", "To drink", "noushidan", "minousham (present)"),
    ("نوشیدن", "نوشیدم (past)", "To drink", "noushidan", "noushidam (past)"),
    ("پیش بردن", "می‌پیش برم (present)", "To advance", "pish bordan", "mipish boram (present)"),
    ("پیش بردن", "پیش بردم (past)", "To advance", "pish bordan", "pish bordam (past)"),
    ("پناه دادن", "می‌پناه دهم (present)", "To shelter", "panah dadan", "mipanah deham (present)"),
    ("پناه دادن", "پناه دادم (past)", "To shelter", "panah dadan", "panah dadam (past)"),
    ("نمودار کشیدن", "می‌نمودار کشم (present)", "To graph", "namoodar keshidan", "minamoodar kesham (present)"),
    ("نمودار کشیدن", "نمودار کشیدم (past)", "To graph", "namoodar keshidan", "namoodar keshidam (past)"),
    ("چاپ کردن", "می‌چاپم (present)", "To print", "chaap kardan", "michaapam (present)"),
    ("چاپ کردن", "چاپ کردم (past)", "To print", "chaap kardan", "chaap kardam (past)"),
    ("برش دادن", "می‌برش دهم (present)", "To cut", "borsh dadan", "miborsh deham (present)"),
    ("برش دادن", "برش دادم (past)", "To cut", "borsh dadan", "borsh dadam (past)"),
    ("مسافرت کردن", "می‌مسافرت کنم (present)", "To tour", "mosaferat kardan", "mimosaferat konam (present)"),
    ("مسافرت کردن", "مسافرت کردم (past)", "To tour", "mosaferat kardan", "mosaferat kardam (past)"),
    ("عکس گرفتن", "می‌عکس بگیرم (present)", "To photograph", "aks gereftan", "miaks begiram (present)"),
    ("عکس گرفتن", "عکس گرفتم (past)", "To photograph", "aks gereftan", "aks gereftam (past)"),
    ("نقاشی کردن", "می‌نقاشی کنم (present)", "To paint", "naqashi kardan", "minaqashi konam (present)"),
    ("نقاشی کردن", "نقاشی کردم (past)", "To paint", "naqashi kardan", "naqashi kardam (past)"),
    ("بخواندن", "می‌بخوانم (present)", "To recite", "bekhondan", "mibekhondam (present)"),
    ("بخواندن", "بخواندم (past)", "To recite", "bekhondan", "bakhondam (past)"),
    ("خوابیدن", "می‌خوابم (present)", "To sleep", "khabidan", "mikhobam (present)"),
    ("خوابیدن", "خوابیدم (past)", "To sleep", "khabidan", "khobidam (past)"),
    ("درخت زدن", "می‌درخت بزنم (present)", "To graft", "derakht zadan", "midarakhth bezanam (present)"),
    ("درخت زدن", "درخت زدم (past)", "To graft", "derakht zadan", "darakhth zadam (past)"),
    ("آغاز کردن", "می‌آغازم (present)", "To commence", "aghaz kardan", "miaghazam (present)"),
    ("آغاز کردن", "آغاز کردم (past)", "To commence", "aghaz kardan", "aghaz kardam (past)"),
    ("فریاد زدن", "می‌فریاد بزنم (present)", "To scream", "faryad zadan", "mifaryad bezanam (present)"),
    ("فریاد زدن", "فریاد زدم (past)", "To scream", "faryad zadan", "faryad zadam (past)"),
    ("زنگ زدن", "می‌زنگ بزنم (present)", "To ring", "zang zadan", "mizang bezanam (present)"),
    ("زنگ زدن", "زنگ زدم (past)", "To ring", "zang zadan", "zang zadam (past)"),
    ("پوشیدن", "می‌پوشم (present)", "To wear", "pooshidan", "mipoosham (present)"),
    ("پوشیدن", "پوشیدم (past)", "To wear", "pooshidan", "pooshidam (past)"),
    ("عصبانی شدن", "می‌عصبانی شوم (present)", "To get angry", "asabani shodan", "miasabani shavam (present)"),
    ("عصبانی شدن", "عصبانی شدم (past)", "To get angry", "asabani shodan", "asabani shodam (past)"),
    ("خیس کردن", "می‌خیس کنم (present)", "To soak", "khis kardan", "mikhis konam (present)"),
    ("خیس کردن", "خیس کردم (past)", "To soak", "khis kardan", "khis kardam (past)"),
    ("گریه کردن", "می‌گریم (present)", "To cry", "gerye kardan", "migeream (present)"),
    ("گریه کردن", "گریه کردم (past)", "To cry", "gerye kardan", "gerye kardam (past)"),
    ("نالیدن", "می‌نالم (present)", "To moan", "naalidan", "minalam (present)"),
    ("نالیدن", "نالیدم (past)", "To moan", "naalidan", "naalidam (past)"),
    ("لباس پوشیدن", "می‌لباس بپوشم (present)", "To dress", "lebaas pooshidan", "milebaas bepoosham (present)"),
    ("لباس پوشیدن", "لباس پوشیدم (past)", "To dress", "lebaas pooshidan", "lebaas pooshidam (past)"),
    ("خفه شدن", "می‌خفه شوم (present)", "To choke", "khofe shodan", "mikhofe shavam (present)"),
    ("خفه شدن", "خفه شدم (past)", "To choke", "khofe shodan", "khofe shodam (past)"),
    ("سر زدن", "می‌سر بزنم (present)", "To brainstorm", "sar zadan", "misar bezanam (present)"),
    ("سر زدن", "سر زدم (past)", "To brainstorm", "sar zadan", "sar zadam (past)"),
    ("پوکیدن", "می‌پوکم (present)", "To rot", "pookidan", "mipookam (present)"),
    ("پوکیدن", "پوکیدم (past)", "To rot", "pookidan", "pookidam (past)"),
    ("چمیدن", "می‌چمم (present)", "To forage", "chamidan", "michammam (present)"),
    ("چمیدن", "چمیدم (past)", "To forage", "chamidan", "chammidam (past)"),
    ("گذاشتن", "می‌گذارم (present)", "To set", "gozashtan", "migozaram (present)"),
    ("گذاشتن", "گذاشتم (past)", "To set", "gozashtan", "gozashtam (past)"),
    ("پرسیدن", "می‌پرسم (present)", "To ask", "persidan", "miporsam (present)"),
    ("پرسیدن", "پرسیدم (past)", "To ask", "persidan", "persidam (past)"),
    ("می‌دویدن", "می‌دویم (present)", "To jog", "dozdan", "midavim (present)"),
    ("می‌دویدن", "دویدم (past)", "To jog", "dozdan", "davidam (past)"),
    ("کشیدن", "می‌کشم (present)", "To haul", "keshidan", "mikesham (present)"),
    ("کشیدن", "کشیدم (past)", "To haul", "keshidan", "keshidam (past)"),
    ("سوزاندن", "می‌سوزانم (present)", "To ignite", "souzaandan", "misouzaanam (present)"),
    ("سوزاندن", "سوزاندم (past)", "To ignite", "souzaandan", "souzaandam (past)"),
    ("کشتن", "می‌کشم (present)", "To slay", "koshtan", "mikosham (present)"),
    ("کشتن", "کشتم (past)", "To slay", "koshtan", "koshtam (past)"),
    ("دویدن", "می‌دوم (present)", "To sprint", "davidan", "midavam (present)"),
    ("دویدن", "دویدم (past)", "To sprint", "davidan", "davidam (past)"),
    ("چکیدن", "می‌چکم (present)", "To strain", "chekidan", "michekam (present)"),
    ("چکیدن", "چکیدم (past)", "To strain", "chekidan", "chekidam (past)"),
    ("چسباندن", "می‌چسبانم (present)", "To affix", "chasbandan", "michasbanam (present)"),
    ("چسباندن", "چسباندم (past)", "To affix", "chasbandan", "chasbandam (past)"),
    ("رفتار کردن", "می‌رفتار کنم (present)", "To behave", "raftaar kardan", "mirafaar konam (present)"),
    ("رفتار کردن", "رفتار کردم (past)", "To behave", "raftaar kardan", "raftaar kardam (past)"),
    ("نزدیک شدن", "می‌نزدیک شوم (present)", "To approach", "nazdik shodan", "minazdik shavam (present)"),
    ("نزدیک شدن", "نزدیک شدم (past)", "To approach", "nazdik shodan", "nazdik shodam (past)"),
    ("شستن", "می‌شوم (present)", "To launder", "shostan", "mishavam (present)"),
    ("شستن", "شستم (past)", "To launder", "shostan", "shastam (past)"),
    ("بریدن", "می‌برم (present)", "To shear", "boridan", "mibaram (present)"),
    ("بریدن", "بریدم (past)", "To shear", "boridan", "boridam (past)"),
    ("نفرین کردن", "می‌نفرین کنم (present)", "To curse", "nefrin kardan", "minefrin konam (present)"),
    ("نفرین کردن", "نفرین کردم (past)", "To curse", "nefrin kardan", "nefrin kardam (past)"),
    ("پس‌دهدن", "می‌پس‌دهم (present)", "To rebound", "pasdadan", "mipsdaham (present)"),
    ("پس‌دهدن", "پس‌دهدم (past)", "To rebound", "pasdadan", "pasdahdam (past)"),
    ("گردآوری کردن", "می‌گردآوری کنم (present)", "To collect", "gardaavar kardan", "migardaavar konam (present)"),
    ("گردآوری کردن", "گردآوری کردم (past)", "To collect", "gardaavar kardan", "gardaavar kardam (past)"),
    ("خود کشی کردن", "می‌خود کشی کنم (present)", "To commit suicide", "khodkoshi kardan", "mikhodkoshi konam (present)"),
    ("خود کشی کردن", "خود کشی کردم (past)", "To commit suicide", "khodkoshi kardan", "khodkoshi kardam (past)"),
    ("جوانه زدن", "می‌جوانه بزنم (present)", "To sprout", "javaneh zadan", "mijavaneh bezanam (present)"),
    ("جوانه زدن", "جوانه زدم (past)", "To sprout", "javaneh zadan", "javaneh zadam (past)"),
    ("سکوت کردن", "می‌سکوت کنم (present)", "To hush", "sokoot kardan", "misokoot konam (present)"),
    ("سکوت کردن", "سکوت کردم (past)", "To hush", "sokoot kardan", "sokoot kardam (past)"),
    ("فریاد زدن", "می‌فریاد بزنم (present)", "To shout", "faryad zadan", "mifaryad bezanam (present)"),
    ("فریاد زدن", "فریاد زدم (past)", "To shout", "faryad zadan", "faryad zadam (past)"),
    ("خارج کردن", "می‌خارج کنم (present)", "To eject", "khaarj kardan", "mikhaarj konam (present)"),
    ("خارج کردن", "خارج کردم (past)", "To eject", "khaarj kardan", "khaarj kardam (past)"),
    ("کلک کردن", "می‌کلک کنم (present)", "To cluck", "kalek kardan", "mikalek konam (present)"),
    ("کلک کردن", "کلک کردم (past)", "To cluck", "kalek kardan", "kalek kardam (past)"),
    ("پرت کردن", "می‌پرت کنم (present)", "To fling", "part kardan", "mipart konam (present)"),
    ("پرت کردن", "پرت کردم (past)", "To fling", "part kardan", "part kardam (past)"),
    ("چماق زدن", "می‌چماق بزنم (present)", "To club", "chamaagh zadan", "michamaagh bezanam (present)"),
    ("چماق زدن", "چماق زدم (past)", "To club", "chamaagh zadan", "chamaagh zadam (past)"),
    ("گریه کردن", "می‌گریم (present)", "To weep", "gerye kardan", "migeream (present)"),
    ("گریه کردن", "گریه کردم (past)", "To weep", "gerye kardan", "gerye kardam (past)"),
    ("دعوا کردن", "می‌دعوا کنم (present)", "To quarrel", "dou'a kardan", "midou'a konam (present)"),
    ("دعوا کردن", "دعوا کردم (past)", "To quarrel", "dou'a kardan", "dou'a kardam (past)"),
    ("فریاد زدن", "می‌فریاد بزنم (present)", "To shriek", "faryad zadan", "mifaryad bezanam (present)"),
    ("فریاد زدن", "فریاد زدم (past)", "To shriek", "faryad zadan", "faryad zadam (past)"),
    ("بلعیدن", "می‌بلعم (present)", "To gulp", "bol'idan", "mibol'am (present)"),
    ("بلعیدن", "بلعیدم (past)", "To gulp", "bol'idan", "bol'idam (past)"),
    ("دست زدن", "می‌دست می‌زنم (present)", "To smack", "dast zadan", "midast mizanam (present)"),
    ("دست زدن", "دست زدم (past)", "To smack", "dast zadan", "dast zadam (past)"),
    ("زمزمه کردن", "می‌زمزمه می‌کنم (present)", "To murmur", "zamzameh kardan", "mizamzameh mikonam (present)"),
    ("زمزمه کردن", "زمزمه کردم (past)", "To murmur", "zamzameh kardan", "zamzameh kardam (past)"),
    ("ترتیب دادن", "می‌ترتیب می‌دهم (present)", "To arrange", "tartib dadan", "mitartib mideham (present)"),
    ("ترتیب دادن", "ترتیب دادم (past)", "To arrange", "tartib dadan", "tartib dadam (past)"),
    ("بیماری کشیدن", "می‌بیماری کشم (present)", "To ail", "bimaari keshidan", "mibiimaari kosham (present)"),
    ("بیماری کشیدن", "بیماری کشیدم (past)", "To ail", "bimaari keshidan", "bimaari keshidam (past)"),
    ("تقلب کردن", "می‌تقلب می‌کنم (present)", "To cheat", "taghallob kardan", "mitaghallob mikonam (present)"),
    ("تقلب کردن", "تقلب کردم (past)", "To cheat", "taghallob kardan", "taghallob kardam (past)"),
    ("نهادن", "می‌نهادم (present)", "To lay", "nehadan", "minehadam (present)"),
    ("نهادن", "نهادم (past)", "To lay", "nehadan", "nehadam (past)"),
    ("بداختن", "می‌بداختم (present)", "To paddle", "bedaakhtan", "mibedaakhtam (present)"),
    ("بداختن", "بداختم (past)", "To paddle", "bedaakhtan", "bedaakhtam (past)"),
    ("آب شدن", "می‌آب شوم (present)", "To melt", "aab shodan", "miaab shavam (present)"),
    ("آب شدن", "آب شدم (past)", "To melt", "aab shodan", "aab shodam (past)"),
    ("خشک شدن", "می‌خشک شوم (present)", "To dry", "khoshk shodan", "mikhoshk shavam (present)"),
    ("خشک شدن", "خشک شدم (past)", "To dry", "khoshk shodan", "khoshk shodam (past)"),
    ("پرسیدن", "می‌پرسم (present)", "To inquire", "persidan", "miporsam (present)"),
    ("پرسیدن", "پرسیدم (past)", "To inquire", "persidan", "persidam (past)"),
    ("خم کردن", "می‌خم می‌کنم (present)", "To bow", "kham kardan", "mikham mikonam (present)"),
    ("خم کردن", "خم کردم (past)", "To bow", "kham kardan", "kham kardam (past)"),
    ("بیرون رفتن", "می‌بروم (present)", "To exit", "birun raftan", "mibaram (present)"),
    ("بیرون رفتن", "بیرون رفتم (past)", "To exit", "birun raftan", "birun raftam (past)"),
    ("می‌خیسم", "می‌خیسم (present)", "To drench", "mikhisam", "mikhisam (present)"),
    ("می‌خیسم", "خیسم (past)", "To drench", "mikhisam", "khisam (past)"),
    ("می‌سوزم", "می‌سوزم (present)", "To combust", "misozam", "misozam (present)"),
    ("می‌سوزم", "سوزم (past)", "To combust", "misozam", "sozam (past)"),
    ("می‌کشم", "می‌کشم (present)", "To drag", "mikesham", "mikesham (present)"),
    ("می‌کشم", "کشم (past)", "To drag", "mikesham", "kesham (past)"),
    ("می‌آشوبم", "می‌آشوبم (present)", "To riot", "miaashubam", "miaashubam (present)"),
    ("می‌آشوبم", "آشوبم (past)", "To riot", "miaashubam", "aashubam (past)"),
    ("می‌خندم", "می‌خندم (present)", "To chuckle", "mikhondam", "mikhondam (present)"),
    ("می‌خندم", "خندم (past)", "To chuckle", "mikhondam", "khondam (past)"),
    ("می‌خمیرم", "می‌خمیرم (present)", "To knead", "mikhamiram", "mikhamiram (present)"),
    ("می‌خمیرم", "خمیرم (past)", "To knead", "mikhamiram", "khamiram (past)"),
    ("می‌زنم", "می‌زنم (present)", "To bang", "mizanam", "mizanam (present)"),
    ("می‌زنم", "زنم (past)", "To bang", "mizanam", "zanam (past)")
]



# Create a CSV file and write the data
with open('anki_verbs_present_past.csv', mode='w', encoding='utf-8', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["English Phonetic", "English Translation"])
    for verb_data_entry in verb_data:
        verb, tense, translation, phonetic_past, phonetic_tense = verb_data_entry
        writer.writerow([f"{tense}" " " f"{phonetic_tense}", f"{translation}"])
        #writer.writerow([f"{tense}", translation])

print("Anki-compatible CSV file with verbs created successfully!")
